- alias: Power state on HA start-up
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffs/state
      payload: ''
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffs/POWER
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffs/POWER2
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffs/POWER3
  id: 8ae9dc0a910341228ff342cb7d27e2d3
  
- alias: Tasmota versions on HA start-up
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffs/STATUS
      payload: '2'
  id: c21df24d3f444ab7af35cddb924a1f7d
- alias: Sonoff IPs on HA start-up
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffs/ipaddress
      payload: ''
  id: faf8a1d80157482c8dd0a0dcc3f34270

- id: '1572786257007'
  alias: Redémarrage
  description: ''
  trigger:
    platform: homeassistant
    event: start
  action:
  - alias: ''
    data:
      data:
        push:
          badge: 5
          thread-id: home-assistant
        subtitle: Démarrage terminé
      message: Le redémarrage était-il intentionnel?
      title: Redémarrage de Home Assistant
    service: notify.ios_iphone_de_le_gone

- alias: Risque de pluie
  trigger:
    platform: time
    at: 07:30:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: switch.conchita_schedule
    state: 'on'
  - condition: numeric_state
    entity_id: sensor.nice_rain_chance
    above: 20
  action:
  - alias: ''
    data:
      data:
        push:
          badge: 5
          thread-id: home-assistant
      message: Pense à prendre ton blouson de moto étanche
      title: Risque de pluie
    service: notify.ios_iphone_de_le_gone
  id: 6fbc85b1b12f43ff83421c7e0879c21b

- alias: Il pleut
  trigger:
    platform: time
    at: 07:25:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: switch.conchita_schedule
    state: 'on'
  - condition: state
    entity_id: sensor.nice_weather
    state: Pluie
  action:
  - alias: ''
    data:
      data:
        push:
          badge: 5
          thread-id: home-assistant
      message: Habillez vous en conséquence
      title: Il pleut dehors
    service: notify.ios_iphone_de_le_gone
  - service: notify.alexa_media_echo_de_marina
    data:
      target: media_player.alexa
      message: Attention, il pleut dehors.
      data:
        type: announce
        method: all
  id: 41d536435d6346bca25d4eabb55c7d35

- alias: Temps de trajet
  trigger:
    platform: time
    at: "07:32:00"
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: switch.conchita_schedule
    state: 'on'
  action:
  - alias: ''
    service: notify.ios_iphone_de_le_gone
    data:
      message: '{{ states(''sensor.fabrice_to_work'') }} minutes'
      title: Temps de trajet estimé
      data:
        push:
          badge: 5
          thread-id: home-assistant
  - service: notify.alexa_media_echo_de_marina
    data:
      target: media_player.alexa
      message: Temps de trajet estimé à {{ states('sensor.fabrice_to_work') }} minutes
      data:
        type: announce
        method: all

- alias: Temps de trajet retour
  trigger:
    platform: time
    at: "18:00:00"
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: switch.conchita_schedule
    state: 'on'
  action:
  - alias: ''
    service: notify.ios_iphone_de_le_gone
    data:
      message: '{{ states(''sensor.fabrice_to_work'') }} minutes'
      title: Temps de trajet estimé
      data:
        push:
          badge: 5
          thread-id: home-assistant

- alias: Météo du jour
  trigger:
    platform: time
    at: 07:00:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: switch.conchita_schedule
    state: 'on'
  action:
  - service: notify.alexa_media_echo_de_marina
    data:
      target: media_player.alexa
      message: Bonjour! Aujourd'hui il fait {{ states("sensor.nice_temperature") }}
        degrés dehors avec {{ states("sensor.nice_wind_speed") }} km/h de vent. Comptez
        {{ states("sensor.nice_rain_chance") }} % de chances pour qu'il pleuve. Quel
        temps dehors? {{ states("sensor.nice_weather") }}. Temps de trajet estimé?
        {{ states("sensor.fabrice_to_work") }} minutes. Bonne journée!
      data:
        type: announce
        method: all
  id: bca7238164864128b43edb16c3231af9

- id: '1572943897953'
  alias: Conchita se decharge
  description: ''
  trigger:
  - entity_id: sensor.conchita_battery
    from: '1'
    platform: state
    to: '80'
  condition: []
  action:
  - service: notify.ios_iphone_de_le_gone
    data:
      data:
        push:
          badge: 5
          thread-id: home-assistant
      message: Quelqu'un pourrait la remettre sur sa base?
      title: Conchita se décharge anormalement
  - service: notify.alexa_media
    data:
      target: media_player.alexa
      message: Conchita se décharge anormalement. Quelqu'un pourrait la remettre sur
        sa base?
      data:
        type: announce
        method: all

- id: '1572943972632'
  alias: Conchita en erreur
  description: ''
  trigger:
  - entity_id: vacuum.conchita
    from: error
    platform: state
  condition: []
  action:
  - service: notify.alexa_media
    data:
      target: media_player.alexa
      message: Conchita a un soucis, quelqu'un veut bien l'aider?
      data:
        type: announce
        method: all

- alias: Qualité de l'air
  description: ''
  trigger:
  - entity_id: sensor.salon_sc_airquality
    from: '1'
    platform: state
    to: '80'
  condition: []
  action:
  - service: notify.ios_iphone_de_le_gone
    data:
      data:
        push:
          badge: 5
          thread-id: home-assistant
      message: Quelqu'un pourrait ouvrir la fenêtre?
      title: Qualité de l'air insuffisante
  - service: notify.alexa_media
    data:
      target: media_player.alexa
      message: La qualité de l'air semble insuffisante. Quelqu'un pourrait ouvrir
        la fenêtre?
      data:
        type: announce
        method: all

- id: letsencrypt-renewal
  alias: Let's Encrypt Renewal
  trigger:
  - platform: time
    at: "01:23:45"
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt

- alias: Yamaha allumé par erreur
  trigger:
  - entity_id: media_player.rx_v475
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: time
    after: "22:00:00"
    before: "07:00:00"
  - condition: state
    entity_id: media_player.tele
    state: 'off'
  action:
  - service: media_player.turn_off
    data:
      entity_id: media_player.rx_v475
      

- alias: Fabrice maison
  trigger:
  - entity_id: person.fabrice_pipart
    platform: state
    from: 'not_home'
    to: 'home'
  action:
  - service: notify.alexa_media
    data:
      target: media_player.alexa
      message: Bienvenu à, la maison Fabrice!
      data:
        type: announce
        method: all
      
