##################################### Admin



- id: '1572786257007'
  alias: Redémarrage
  description: ''
  trigger:
    platform: homeassistant
    event: start
  action:
  - alias: ''
    data:
      data:
        push:
          badge: 5
          thread-id: home-assistant
        subtitle: Démarrage terminé
      message: Le redémarrage était-il intentionnel?
      title: Redémarrage de Home Assistant
    service: notify.ios_iphone_de_le_gone
  - service: notify.alexa_media_echo_salon
    data:
      target: media_player.alexa
      message: Home Assistant a fini de redémarrer!
      data:
        type: announce
        method: all

- id: letsencrypt-renewal
  alias: Let's Encrypt Renewal
  trigger:
  - platform: time
    at: "01:23:45"
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt


##################################### Météo


- alias: Qualité de l'air
  description: ''
  trigger:
  - entity_id: sensor.salon_sc_airquality
    from: '1'
    platform: state
    to: '80'
  condition: []
  action:
  - service: notify.ios_iphone_de_le_gone
    data:
      data:
        push:
          badge: 5
          thread-id: home-assistant
      message: Quelqu'un pourrait ouvrir la fenêtre?
      title: Qualité de l'air insuffisante
  - service: notify.alexa_media_echo_salon
    data:
      target: media_player.alexa
      message: La qualité de l'air semble insuffisante. Quelqu'un pourrait ouvrir
        la fenêtre?
      data:
        type: announce
        method: all
        
        

- alias: Fabrice maison
  trigger:
  - entity_id: person.fabrice_pipart
    platform: state
    from: 'not_home'
    to: 'home'
  action:
  - service: notify.alexa_media_echo_salon
    data:
      target: media_player.alexa
      message: Bienvenu à la maison Fabrice!
      data:
        type: announce
        method: all


##################################### Alarme


