# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /config

discovery:
ios:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

neato:
  client_id: !secret neato_username
  client_secret: !secret neato_password

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/spotify-card/spotify-card.js
      type: module
    - url: /hacsfiles/spotify-playlist-card/spotify-playlist-card.js
      type: js
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/text-element/text-element.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module

#meteo_france: !include meteo.yaml
shell_command: !include shell.yaml
sensor: !include sensor.yaml

recorder:
  auto_purge: true
  purge_keep_days: 10
  commit_interval: 30
  #  db_url: 'sqlite:///:memory:'
  #  db_url: !secret psql_url
  exclude:
    event_types:
      - service_removed
      #- service_executed
      - platform_discovered
      #- homeassistant_start
      #- homeassistant_stop
      - feedreader
      - service_registered
      #- call_service
      - component_loaded
      - logbook_entry
      - system_log_event
      #- automation_triggered
      #- script_started
      - timer_out_of_sync
      #- state_changed

alexa:
  smart_home: !include alexa.yaml

frontend:
  themes: !include_dir_merge_named themes

# https://techzoom.net/lab/ip-address-calculator/
# device_tracker:
#   - platform: nmap_tracker
#     hosts: 192.168.1.16/31
#     home_interval: 10 # Idem interval_seconds mais en minute pour nmap
#     interval_seconds: 300 # Le temps en secondes entre chaque scan
#     consider_home: 180 # Le temps sans résultat positif, donc considéré comme absent.

#  - platform: bluetooth_tracker
#  - platform: bluetooth_le_tracker

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomi_gateway_mac
      key: !secret xiaomi_gateway_key
