
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

homeassistant:
  customize: !include customize.yaml

discovery:

ios:

http:
  ssl_certificate: !secret my_home_domain_cert
  ssl_key: !secret my_home_domain_key
  base_url: !secret my_home_domain

meteo_france:
  - city: '06200'
    monitored_conditions:
        - rain_chance
        - freeze_chance
        - thunder_chance
        - snow_chance
        - weather
        - next_rain
        - wind_speed
        - temperature
        - uv
        - weather_alert


mqtt:
  broker: !secret mosquitto_ip
  username: sonoff
  password: !secret mqtt
  discovery: true
  discovery_prefix: cmnd

neato:
  username: !secret neato_username
  password: !secret neato_password

light:
  - platform: mqtt
    name: "SàM"
    state_topic: "stat/home/dining/light/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/dining/light/POWER"
    availability_topic: "tele/home/dining/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Cléo"
    state_topic: "stat/home/cleo/light/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/cleo/light/POWER"
    availability_topic: "tele/home/cleo/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Salon"
    state_topic: "stat/home/living/light/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/living/light/POWER"
    availability_topic: "tele/home/living/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Chambre"
    state_topic: "stat/home/parents/light/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/parents/light/POWER"
    availability_topic: "tele/home/parents/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

sensor:
    
  - platform: mqtt
    name: "Salle à Manger (Signal)"
    state_topic: "tele/home/dining/light/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/dining/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Salle à Manger (version)"
    state_topic: "stat/home/dining/light/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/dining/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Salle à Manger (IP)"
    state_topic: 'stat/home/dining/light/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"

  - platform: mqtt
    name: "Salon (Signal)"
    state_topic: "tele/home/living/light/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/living/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Salon (version)"
    state_topic: "stat/home/living/light/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/living/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Salon (IP)"
    state_topic: 'stat/home/living/light/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"

  - platform: mqtt
    name: "Chambre (Signal)"
    state_topic: "tele/home/parents/light/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/parents/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Chambre (version)"
    state_topic: "stat/home/parents/light/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/parents/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Chambre (IP)"
    state_topic: 'stat/home/parents/light/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"

  - platform: mqtt
    name: "Chambre Cléo (Signal)"
    state_topic: "tele/home/cleo/light/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/cleo/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Chambre Cléo (version)"
    state_topic: "stat/home/cleo/light/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/cleo/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Chambre Cléo (IP)"
    state_topic: 'stat/home/cleo/light/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"

  - platform: mqtt
    name: "Salon SC (Signal)"
    state_topic: "tele/home/living/sc/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/living/sc/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Salon SC (version)"
    state_topic: "stat/home/living/sc/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/living/sc/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Salon SC (IP)"
    state_topic: 'stat/home/living/sc/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"
  - platform: mqtt
    name: "Salon SC (Temperature)"
    state_topic: "tele/home/living/sc/SENSOR"
    value_template: "{{ value_json['SonoffSC'].Temperature | float - 3 }}"
    unit_of_measurement: "°C"
    availability_topic: "tele/home/living/sc/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Salon SC (Humidity)"
    state_topic: "tele/home/living/sc/SENSOR"
    value_template: "{{ value_json['SonoffSC'].Humidity }}"
    unit_of_measurement: "%"
    availability_topic: "tele/home/living/sc/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Salon SC (Light)"
    state_topic: "tele/home/living/sc/SENSOR"
    value_template: "{{ value_json['SonoffSC'].Light }}"
    unit_of_measurement: "%"
    availability_topic: "tele/home/living/sc/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Salon SC (Noise)"
    state_topic: "tele/home/living/sc/SENSOR"
    value_template: "{{ value_json['SonoffSC'].Noise }}"
    unit_of_measurement: "%"
    availability_topic: "tele/home/living/sc/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Salon SC (AirQuality)"
    state_topic: "tele/home/living/sc/SENSOR"
    value_template: "{{ value_json['SonoffSC'].AirQuality }}"
    unit_of_measurement: "%"
    availability_topic: "tele/home/living/sc/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /Users
      - type: disk_use_percent
        arg: /Volumes/Media
      - type: disk_use_percent
        arg: /Volumes/Backups
      - type: memory_use_percent
      - type: swap_use_percent
      - type: processor_use
      - type: last_boot
      - type: network_in
      - type: network_out
      - type: throughput_network_in
      - type: throughput_network_out
