
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

homeassistant:
  customize: !include customize.yaml

discovery:
ios:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret my_home_domain

wemo:
  discovery: false

mqtt:
  broker: !secret mosquitto_ip
  username: sonoff
  password: !secret mqtt
  discovery: true
  discovery_prefix: cmnd

neato:
  username: !secret neato_username
  password: !secret neato_password

google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret

lovelace:
  mode: yaml

meteo_france: !include meteo.yaml
media_player: !include media_player.yaml
shell_command: !include shell.yaml
light: !include light.yaml
sensor: !include sensor.yaml
    
alexa:
  smart_home: !include alexa.yaml

frontend:
  themes: !include_dir_merge_named themes

#https://www.ipaddressguide.com/cidr
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.69.128/31
  - platform: bluetooth_tracker
#  - platform: bluetooth_le_tracker

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomi_gateway_mac
      key: !secret xiaomi_gateway_key

# plex:
#   host: 192.168.69.69
#   port: 32400
#   token: !secret plex_token
#   ssl: true
#   verify_ssl: false
#   media_player:
#     use_episode_art: true
#     show_all_controls: false