# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

discovery:
ios:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  #base_url: !secret my_home_domain

mqtt:
  broker: !secret mosquitto_ip
  username: sonoff
  password: !secret mqtt
  discovery: true
  discovery_prefix: cmnd

neato:
  username: !secret neato_username
  password: !secret neato_password

google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret

lovelace:
  mode: yaml

#meteo_france: !include meteo.yaml
shell_command: !include shell.yaml
sensor: !include sensor.yaml

recorder:
  auto_purge: true
  purge_keep_days: 5
  commit_interval: 30
  db_url: 'sqlite:///:memory:'
  exclude:
    event_types:
      - service_removed
      #- service_executed
      - platform_discovered
      #- homeassistant_start
      #- homeassistant_stop      
      - feedreader
      - service_registered
      #- call_service
      - component_loaded
      - logbook_entry
      - system_log_event
      #- automation_triggered
      #- script_started
      - timer_out_of_sync
      #- state_changed
      
alexa:
  smart_home: !include alexa.yaml

frontend:
  themes: !include_dir_merge_named themes

#https://www.ipaddressguide.com/cidr
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.128/31
#  - platform: bluetooth_tracker
#  - platform: bluetooth_le_tracker

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomi_gateway_mac
      key: !secret xiaomi_gateway_key
plex:
#   host: 192.168.1.69
  port: 32400
  token: !secret plex_token
  ssl: true
  verify_ssl: false
  media_player:
    use_episode_art: true
    show_all_controls: false
