- platform: mqtt
  name: "SàM"
  state_topic: "stat/home/dining/light/RESULT"
  state_value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/home/dining/light/POWER"
  availability_topic: "tele/home/dining/light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Cléo"
  state_topic: "stat/home/cleo/light/RESULT"
  state_value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/home/cleo/light/POWER"
  availability_topic: "tele/home/cleo/light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Salon"
  state_topic: "stat/home/living/light/RESULT"
  state_value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/home/living/light/POWER"
  availability_topic: "tele/home/living/light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Chambre"
  state_topic: "stat/home/parents/light/RESULT"
  state_value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/home/parents/light/POWER"
  availability_topic: "tele/home/parents/light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "S20"
  state_topic: "stat/home/s20/light/RESULT"
  state_value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/home/s20/light/POWER"
  availability_topic: "tele/home/s20/light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Entrée 1"
  state_topic: "stat/home/entrance/light1/RESULT"
  state_value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/home/entrance/light1/POWER"
  availability_topic: "tele/home/entrance/light1/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Entrée 2"
  state_topic: "stat/home/entrance/light2/RESULT"
  state_value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/home/entrance/light2/POWER"
  availability_topic: "tele/home/entrance/light2/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Entrée 3"
  state_topic: "stat/home/entrance/light3/RESULT"
  state_value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/home/entrance/light3/POWER"
  availability_topic: "tele/home/entrance/light3/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Cuisine"
  state_topic: "stat/home/kitchen/light/RESULT"
  state_value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/home/kitchen/light/POWER"
  availability_topic: "tele/home/kitchen/light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Salle de Bain"
  state_topic: "stat/home/bathroom/light/RESULT"
  state_value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/home/bathroom/light/POWER"
  availability_topic: "tele/home/bathroom/light/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
