- platform: yamaha
  name: rx_v475
  source_ignore:
    - "AV1"
    - "AV3"
    - "AV5"
    - "AV6"
    - "HDMI4"
    - "HDMI5"
    - "USB"
    - "V-AUX"
    - "iPod (USB)"
  source_names:
    AUDIO: "Wii"
    AV2: "CD"
    AV4: "Sony TV"
    HDMI1: "PS3"
    HDMI2: "Box"
    HDMI3: "Plex"
- platform: braviatv
  host: 192.168.69.65
- platform: spotify
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_secret
