title: Maison
resources:
  - url: /community_plugin/calendar-card/calendar-card.js
    type: js
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module


views:

  - badges: []
    cards:
      - cards:
          - entity: light.sam
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: light.salon
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: light.cleo
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: light.chambre
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
        title: Lumières
        type: horizontal-stack
      - entities:
          - entity: sensor.salon_sc_temperature
        title: Température
        type: glance
      - entities:
          - entity: sensor.salon_sc_humidity
        title: Humidité
        type: glance
      - entities:
          - entity: sensor.salon_sc_light
          - entity: sensor.salon_sc_airquality
          - entity: sensor.salon_sc_noise
        title: Autres
        type: glance
      - entities:
          - entity: sensor.salon_sc_temperature
          - entity: sensor.salon_sc_humidity
        hours_to_show: 72
        refresh_interval: 0
        type: history-graph
    icon: 'mdi:home'
    path: lumieres
    title: Lumières



  - badges: []
    cards:
      - cards:
          - entity: script.neato_cuisine
            hold_action:
              action: more-info
            icon: 'mdi:robot-vacuum-variant'
            icon_height: 48px
            name: Cuisine
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.neato_table
            hold_action:
              action: more-info
            icon: 'mdi:robot-vacuum-variant'
            icon_height: 48px
            name: Table
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.neato_table_basse
            hold_action:
              action: more-info
            icon: 'mdi:robot-vacuum-variant'
            icon_height: 48px
            name: T.Basse
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.neato_sam
            hold_action:
              action: more-info
            icon: 'mdi:robot-vacuum-variant'
            icon_height: 48px
            name: SàM
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.neato_chambre
            hold_action:
              action: more-info
            icon: 'mdi:robot-vacuum-variant'
            icon_height: 48px
            name: Chambre
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
        title: Aspirer zone
        type: horizontal-stack
      - cards:
          - entity: script.neato_cleo
            hold_action:
              action: more-info
            icon: 'mdi:robot-vacuum-variant'
            icon_height: 48px
            name: Cléo
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.neato_couloir
            hold_action:
              action: more-info
            icon: 'mdi:robot-vacuum-variant'
            icon_height: 48px
            name: Couloir
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.neato_entree
            hold_action:
              action: more-info
            icon: 'mdi:robot-vacuum-variant'
            icon_height: 48px
            name: Entrée
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.neato_sdb
            hold_action:
              action: more-info
            icon: 'mdi:robot-vacuum-variant'
            icon_height: 48px
            name: SdB
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.neato_wc
            hold_action:
              action: more-info
            icon: 'mdi:robot-vacuum-variant'
            icon_height: 48px
            name: WC
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
        type: horizontal-stack
      - entities:
          - entity: switch.conchita_schedule
          - entity: vacuum.conchita
          - entity: sensor.conchita_battery
        title: Conchita
        type: entities
      - aspect_ratio: 100%
        camera_image: camera.conchita_cleaning_map
        entity: camera.conchita_cleaning_map
        type: picture-entity
    icon: 'mdi:robot-vacuum-variant'
    panel: false
    title: Aspirateur



  - badges: []
    cards:
      - entity: weather.nice
        name: Météo France
        type: weather-forecast
      - columns: 3
        entities:
          - entity: sun.sun
          - entity: sensor.nice_weather
          - entity: sensor.nice_temperature
          - entity: sensor.nice_wind_speed
          - entity: sensor.nice_rain_chance
          - entity: sensor.nice_uv
        show_name: false
        type: glance
      - entity: weather.maison
        type: weather-forecast
      - entities:
          - entity: switch.alexa_do_not_disturb_switch
          - entity: sensor.alexa_next_alarm
          - entity: sensor.alexa_next_reminder
          - entity: sensor.alexa_next_timer
        show_header_toggle: false
        title: Alexa
        type: entities
      - type: custom:calendar-card
        title: "My Calendar"
        progressBar: true
        numberOfDays: 30
        entities:
          - calendar.fabrice_pipart_gmail_com
          - calendar.calendrier_perso
    icon: 'mdi:weather-rainy'
    panel: false
    path: meteo
    title: Météo

  - badges: []
    cards:
      - title: Activités
        type: horizontal-stack
        cards:
          - entity: script.activity_off
            name: 'Off'
            icon: 'mdi:power'
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.activity_box
            name: Box
            icon: 'mdi:television-box'
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.activity_netflix
            name: Netflix
            icon: 'mdi:netflix'
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.activity_plex
            name: Plex
            icon: 'mdi:plex'
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
      - type: horizontal-stack
        cards:
          - entity: script.activity_amazon
            name: Prime
            icon: 'mdi:amazon'
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.activity_wii
            name: Wii
            icon: 'mdi:wii'
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.activity_youtube
            name: Youtube
            icon: 'mdi:youtube'
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.activity_youtube_kids
            name: Kids
            icon: 'mdi:youtube'
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
      - type: horizontal-stack
        cards:
          - entity: script.activity_ps3
            name: 'PS3'
            icon: 'mdi:playstation'
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.activity_airplay
            name: 'Airplay'
            icon: 'mdi:airplay'
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.activity_spotify
            name: Spotify
            icon: 'mdi:spotify'
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.activity_dlna
            name: iTunes
            icon: 'mdi:itunes'
            hold_action:
              action: more-info
            icon_height: 48px
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
      - type: custom:mini-media-player
        entity: media_player.sony_bravia_tv
      - entities:
          - entity: media_player.alexa
          - entity: switch.alexa_shuffle_switch
          - entity: switch.alexa_repeat_switch
        show_header_toggle: false
        title: Alexa
        type: entities
      - entity: media_player.rx_v475
        type: media-control

    icon: 'mdi:music'
    path: medias
    title: Medias

  - badges: []
    cards:
      - cards:
        - entity: script.sleep_mac
          hold_action:
            action: more-info
          icon: 'mdi:sleep'
          icon_height: 48px
          show_icon: true
          show_name: true
          tap_action:
            action: toggle
          type: entity-button
        title: Aspirer zone
        type: horizontal-stack
      - entities:
          - entity: sensor.neufbox_router_kbyte_sec_sent
          - entity: sensor.neufbox_router_kbyte_sec_received
        show_header_toggle: false
        title: Internet
        type: entities
      - entities:
          - entity: sensor.processor_use
          - entity: sensor.memory_use_percent
          - entity: sensor.swap_use_percent
          - entity: sensor.last_boot
          - entity: sensor.disk_use_percent
        show_header_toggle: false
        title: Raspberry
        type: entities
      - entities:
          - entity: binary_sensor.updater
        show_header_toggle: false
        title: Updater
        type: entities
      - columns: 3
        entities:
          - entity: sensor.salon_sc_signal
          - entity: sensor.salle_a_manger_signal
          - entity: sensor.salon_signal
          - entity: sensor.chambre_signal
          - entity: sensor.chambre_cleo_signal
        show_icon: false
        title: Signal Sonoff
        type: glance
      - columns: 3
        entities:
          - entity: sensor.salle_a_manger_ip
          - entity: sensor.salon_ip
          - entity: sensor.salon_sc_ip
          - entity: sensor.chambre_cleo_ip
          - entity: sensor.chambre_ip
        show_icon: false
        title: IPs Sonoff
        type: glance
      - columns: 3
        entities:
          - entity: sensor.salle_a_manger_version
          - entity: sensor.salon_version
          - entity: sensor.salon_sc_version
          - entity: sensor.chambre_version
          - entity: sensor.chambre_cleo_version
        show_icon: false
        title: Versions Sonoff
        type: glance
      - entities:
          - entity: sensor.iphone_de_le_gone_battery_level
          - entity: sensor.iphone_de_marina_battery_level
          - entity: sensor.iphone_de_marina_battery_state
        show_header_toggle: false
        title: iPhone
        type: entities
      - entities:
          - entity: automation.power_state_on_ha_start_up
          - entity: automation.tasmota_versions_on_ha_start_up
          - entity: automation.sonoff_ips_on_ha_start_up
          - entity: automation.il_pleut
          - entity: automation.meteo_du_jour
          - entity: automation.redemarrage
          - entity: automation.risque_de_pluie
        type: entities
    icon: 'mdi:network'
    path: reseau
    title: Réseau

  - badges: []
    cards:
      - entities:
          - switch.conchita_schedule
          - sensor.conchita_battery
          - vacuum.conchita
        show_header_toggle: true
        title: Cuisine
        type: entities
      - entity: camera.conchita_cleaning_map
        type: picture-entity
      - entities:
          - sensor.neufbox_router_kbyte_sec_sent
          - sensor.neufbox_router_kbyte_sec_received
        show_header_toggle: true
        title: Salon
        type: entities
      - entity: media_player.tele
        type: media-control
      - entity: media_player.rx_v475
        type: media-control
      - entities:
          - sun.sun
          - sensor.nice_weather
          - sensor.nice_temperature
          - sensor.nice_wind_speed
          - sensor.nice_rain_chance
          - sensor.nice_weather_alert
          - sensor.nice_uv
          - sensor.nice_snow_chance
          - sensor.nice_thunder_chance
          - sensor.nice_next_rain
          - sensor.nice_freeze_chance
        show_header_toggle: true
        title: Météo
        type: entities
      - entity: weather.nice
        type: weather-forecast
      - entities:
          - sensor.salle_a_manger_signal
          - sensor.salle_a_manger_ip
          - sensor.salle_a_manger_version
          - sensor.salon_signal
          - sensor.salon_ip
          - sensor.salon_version
          - sensor.chambre_signal
          - sensor.chambre_ip
          - sensor.chambre_version
          - sensor.chambre_cleo_signal
          - sensor.chambre_cleo_ip
          - sensor.chambre_cleo_version
          - sensor.salon_sc_signal
          - sensor.salon_sc_ip
          - sensor.salon_sc_version
        show_header_toggle: true
        title: Sonoffs
        type: entities
      - entities:
          - sensor.conchita_battery
          - switch.conchita_schedule
          - vacuum.conchita
          - script.neato_chambre
          - script.neato_cleo
          - script.neato_couloir
          - script.neato_cuisine
          - script.neato_entree
          - script.neato_sam
          - script.neato_sdb
          - script.neato_table
          - script.neato_table_basse
          - script.neato_wc
        show_header_toggle: true
        title: Conchita
        type: entities
      - entities:
          - binary_sensor.updater
        show_header_toggle: true
        title: Updater
        type: entities
      - entities:
          - entity: person.fabrice_pipart
          - entity: person.marina_pipart
        show_header_toggle: true
        title: Utilisateurs
        type: entities
      - entities:
          - sensor.plex_hackintosh
        show_header_toggle: true
        title: Plex
        type: entities
      - entity: media_player.plex_openpht
        type: media-control
      - entities:
          - sensor.salon_sc_temperature
          - sensor.salon_sc_humidity
          - sensor.salon_sc_airquality
          - sensor.salon_sc_light
          - sensor.salon_sc_noise
        show_header_toggle: true
        title: Salon
        type: entities
      - entities:
          - sensor.iphone_de_le_gone_battery_level
        show_header_toggle: true
        title: iPhone
        type: entities
      - entities:
          - automation.sonoff_ips_on_ha_start_up
          - automation.power_state_on_ha_start_up
          - automation.tasmota_versions_on_ha_start_up
        title: Automatisation
        type: entities
      - entities:
          - entity: light.sam
          - entity: light.salon
          - entity: light.cleo
          - entity: light.chambre
        title: Lumière
        type: entities
      - entity: weather.maison
        type: weather-forecast
      - entities:
          - entity: switch.alexa_do_not_disturb_switch
          - entity: media_player.alexa
          - entity: switch.alexa_shuffle_switch
          - entity: switch.alexa_repeat_switch
          - entity: sensor.alexa_next_alarm
          - entity: sensor.alexa_next_reminder
          - entity: sensor.alexa_next_timer
        type: entities
      - entities:
          - entity: calendar.fabrice_pipart_gmail_com
        type: entities
    icon: 'mdi:folder-open'
    path: default_view
    title: Home

