title: Maison
resources:
  - url: /hacsfiles/calendar-card/calendar-card.js
    type: js
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /hacsfiles/spotify-card/spotify-card.js
    type: module
  - url: /hacsfiles/spotify-playlist-card/spotify-playlist-card.js
    type: js
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/text-element/text-element.js
    type: module
  - url: /hacsfiles/content-card-linky/content-card-linky.js
    type: module

views: !include_dir_list ui-lovelace/
