###############################################################
# Sensor
###############################################################

sensor:
  #   - platform: sql
  #     db_url: !secret psql_url
  #     queries:
  #       - name: DB size
  #         query: "SELECT (pg_database_size('homeassistant')/1024/1024) as db_size"
  #         column: "db_size"
  #         unit_of_measurement: MB

  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db

###############################################################
# Automation
###############################################################

automation:
  - id: "1572786257007"
    alias: Redémarrage
    description: ""
    trigger:
      platform: homeassistant
      event: start
    action:
      - alias: ""
        data:
          data:
            push:
              badge: 5
              thread-id: home-assistant
            subtitle: Démarrage terminé
          message: Le redémarrage était-il intentionnel?
          title: Redémarrage de Home Assistant
        service: notify.ios_iphone_de_le_gone
      - service: notify.alexa_media_echo_salon
        data:
          message: Home Assistant a fini de redémarrer!
          data:
            type: announce

  - id: letsencrypt-renewal
    alias: Let's Encrypt Renewal
    trigger:
      - platform: time
        at: "01:23:45"
    action:
      - service: hassio.addon_restart
        data:
          addon: core_letsencrypt
