
###############################################################
# Sensors
###############################################################

sensor:
  
  - platform: mqtt
    name: "Salle à Manger (Signal)"
    state_topic: "tele/home/dining/light/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/dining/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:access-point'
  - platform: mqtt
    name: "Salle à Manger (version)"
    state_topic: "stat/home/dining/light/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/dining/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:xml'
  - platform: mqtt
    name: "Salle à Manger (IP)"
    state_topic: 'stat/home/dining/light/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"
    icon: 'mdi:ip-network'
  
  - platform: mqtt
    name: "Salon (Signal)"
    state_topic: "tele/home/living/light/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/living/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:access-point'
  - platform: mqtt
    name: "Salon (version)"
    state_topic: "stat/home/living/light/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/living/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:xml'
  - platform: mqtt
    name: "Salon (IP)"
    state_topic: 'stat/home/living/light/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"
    icon: 'mdi:ip-network'
  
  - platform: mqtt
    name: "Chambre (Signal)"
    state_topic: "tele/home/parents/light/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/parents/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:access-point'
  - platform: mqtt
    name: "Chambre (version)"
    state_topic: "stat/home/parents/light/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/parents/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:xml'
  - platform: mqtt
    name: "Chambre (IP)"
    state_topic: 'stat/home/parents/light/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"
    icon: 'mdi:ip-network'
  
  - platform: mqtt
    name: "Chambre Cléo (Signal)"
    state_topic: "tele/home/cleo/light/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/cleo/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:access-point'
  - platform: mqtt
    name: "Chambre Cléo (version)"
    state_topic: "stat/home/cleo/light/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/cleo/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:xml'
  - platform: mqtt
    name: "Chambre Cléo (IP)"
    state_topic: 'stat/home/cleo/light/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"
    icon: 'mdi:ip-network'
    
  - platform: mqtt
    name: "Couloir (Signal)"
    state_topic: "tele/home/corridor/light/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/corridor/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:access-point'
  - platform: mqtt
    name: "Couloir (version)"
    state_topic: "stat/home/corridor/light/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/corridor/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:xml'
  - platform: mqtt
    name: "Couloir (IP)"
    state_topic: 'stat/home/corridor/light/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"
    icon: 'mdi:ip-network'
  
  - platform: mqtt
    name: "S20 (Signal)"
    state_topic: "tele/home/s20/light/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/s20/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:access-point'
  - platform: mqtt
    name: "S20 (version)"
    state_topic: "stat/home/s20/light/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/s20/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:xml'
  - platform: mqtt
    name: "S20 (IP)"
    state_topic: 'stat/home/s20/light/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"
    icon: 'mdi:ip-network'
  
  - platform: mqtt
    name: "Entrée 1 (Signal)"
    state_topic: "tele/home/entrance/light1/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/entrance/light1/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:access-point'
  - platform: mqtt
    name: "Entrée 1 (version)"
    state_topic: "stat/home/entrance/light1/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/entrance/light1/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:xml'
  - platform: mqtt
    name: "Entrée 1 (IP)"
    state_topic: 'stat/home/entrance/light1/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"
    icon: 'mdi:ip-network'
  
  - platform: mqtt
    name: "Entrée 2 (Signal)"
    state_topic: "tele/home/entrance/light2/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/entrance/light2/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:access-point'
  - platform: mqtt
    name: "Entrée 2 (version)"
    state_topic: "stat/home/entrance/light2/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/entrance/light2/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:xml'
  - platform: mqtt
    name: "Entrée 2 (IP)"
    state_topic: 'stat/home/entrance/light2/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"
    icon: 'mdi:ip-network'
  
  - platform: mqtt
    name: "Entrée 3 (Signal)"
    state_topic: "tele/home/entrance/light3/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/entrance/light3/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:access-point'
  - platform: mqtt
    name: "Entrée 3 (version)"
    state_topic: "stat/home/entrance/light3/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/entrance/light3/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:xml'
  - platform: mqtt
    name: "Entrée 3 (IP)"
    state_topic: 'stat/home/entrance/light3/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"
    icon: 'mdi:ip-network'
  
  - platform: mqtt
    name: "Cuisine (Signal)"
    state_topic: "tele/home/kitchen/light/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/kitchen/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:access-point'
  - platform: mqtt
    name: "Cuisine (version)"
    state_topic: "stat/home/kitchen/light/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/kitchen/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:xml'
  - platform: mqtt
    name: "Cuisine (IP)"
    state_topic: 'stat/home/kitchen/light/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"
    icon: 'mdi:ip-network'
  
  - platform: mqtt
    name: "Salle de Bain (Signal)"
    state_topic: "tele/home/bathroom/light/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/bathroom/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:access-point'
  - platform: mqtt
    name: "Salle de Bain (version)"
    state_topic: "stat/home/bathroom/light/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/bathroom/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:xml'
  - platform: mqtt
    name: "Salle de Bain (IP)"
    state_topic: 'stat/home/bathroom/light/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"
    icon: 'mdi:ip-network'
  
  - platform: mqtt
    name: "WC (Signal)"
    state_topic: "tele/home/wc/light/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/wc/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:access-point'
  - platform: mqtt
    name: "WC (version)"
    state_topic: "stat/home/wc/light/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/wc/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:xml'
  - platform: mqtt
    name: "WC (IP)"
    state_topic: 'stat/home/wc/light/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"
    icon: 'mdi:ip-network'
  
  - platform: mqtt
    name: "WC Wall (Signal)"
    state_topic: "tele/home/wc-wall/light/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/wc-wall/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:access-point'
  - platform: mqtt
    name: "WC Wall (version)"
    state_topic: "stat/home/wc-wall/light/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/wc-wall/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:xml'
  - platform: mqtt
    name: "WC Wall (IP)"
    state_topic: 'stat/home/wc-wall/light/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"
    icon: 'mdi:ip-network'
  
  - platform: mqtt
    name: "Chaussures (Signal)"
    state_topic: "tele/home/shoes/light/STATE"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/home/shoes/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:access-point'
  - platform: mqtt
    name: "Chaussures (version)"
    state_topic: "stat/home/shoes/light/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability_topic: "tele/home/shoes/light/LWT"
    qos: 0
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: 'mdi:xml'
  - platform: mqtt
    name: "Chaussures (IP)"
    state_topic: 'stat/home/shoes/light/RESULT'
    value_template: "{{ value_json.IPAddress1.split(' (')[1].replace('(','').replace(')','') }}"
    icon: 'mdi:ip-network'
  
    
    
###############################################################
# Automation
###############################################################
      
automation:

  - alias: Power state on HA start-up
    trigger:
      platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/state
        payload: ''
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER2
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER3
    id: 8ae9dc0a910341228ff342cb7d27e2d3
    
  - alias: Tasmota versions on HA start-up
    trigger:
      platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/STATUS
        payload: '2'
    id: c21df24d3f444ab7af35cddb924a1f7d
  - alias: Sonoff IPs on HA start-up
    trigger:
      platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/ipaddress
        payload: ''
    id: faf8a1d80157482c8dd0a0dcc3f34270
    
