###############################################################
# Alarm
###############################################################
alarm_control_panel:
  - platform: manual
    name: Maison
    code_arm_required: false
    code: !secret alarm_code
    arming_time: 30
    delay_time: 30
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_night:
      arming_time: 0
      delay_time: 15

###############################################################
# Inputs
###############################################################

### Input select pour choisir le son a jouer ###
input_select:
  sirenes_gateway:
    name: Sirènes
    options:
      - "0 - Police car 1"
      - "1 - Police car 2"
      - "2 - Accident"
      - "3 - Countdown"
      - "4 - Ghost"
      - "5 - Sniper rifle"
      - "6 - Battle"
      - "7 - Air raid"
      - "8 - Bark"
      #    - "9 - None"
      - "10 - Doorbell"
      - "11 - Knock at a door"
      - "12 - Amuse"
      - "13 - Alarm clock"
      #    - "14 - None"
      #    - "15 - None"
      #    - "16 - None"
      #    - "17 - None"
      #    - "18 - None"
      #    - "19 - None"
      - "20 - MiMix"
      - "21 - Enthusiastic"
      - "22 - GuitarClassic"
      - "23 - IceWorldPiano"
      - "24 - LeisureTime"
      - "25 - ChildHood"
      - "26 - MorningStreamLiet"
      - "27 - MusicBox"
      - "28 - Orange"
      - "29 - Thinker"
    initial: "1 - Police car 2"
    icon: mdi:alarm-bell

### Input boolean pour couper le son du gateway ###
input_boolean:
  sourdine_sirenes_gateway:
    name: Muet
    icon: mdi:volume-off

### Input slider pour controler le volu me du gateway ###
input_number:
  gateway_volume:
    name: Volume
    initial: 1
    min: 0
    max: 100
    step: 1
    icon: mdi:volume-high
  ### Input slider pour controler le delai de la boucle ###
  delai_boucle:
    name: "Délai boucle"
    initial: 1
    min: 0
    max: 15
    step: 1
    icon: mdi:loop

###############################################################
# Scripts
###############################################################

script:
  ### Scripts pour jouer les sons du gateway ###
  jouer_sirene:
    alias: "[Alarme] Jouer sirène une fois"
    sequence:
      - service: xiaomi_aqara.play_ringtone
        data_template:
          gw_mac: !secret xiaomi_gateway_mac
          ringtone_id: "{{ states.input_select.sirenes_gateway.state.split('-')[0] }}"
          ringtone_vol: "{{ states.input_number.gateway_volume.state|int }}"

  jouer_sirene_boucle:
    alias: "[Alarme] Jouer sirène en boucle"
    sequence:
      - condition: state
        entity_id: input_boolean.sourdine_sirenes_gateway
        state: "off"
      - service: xiaomi_aqara.play_ringtone
        data_template:
          gw_mac: !secret xiaomi_gateway_mac
          ringtone_id: "{{ states.input_select.sirenes_gateway.state.split('-')[0] }}"
          ringtone_vol: "{{ states.input_number.gateway_volume.state|int }}"
      - delay: "00:00:{{ states.input_number.delai_boucle.state | int }}"
      - service: script.boucle_sirene

  boucle_sirene:
    alias: "[Alarme] Boucle de sirène"
    sequence:
      - condition: state
        entity_id: input_boolean.sourdine_sirenes_gateway
        state: "off"
      - delay: "00:00:{{ states.input_number.delai_boucle.state | int }}"
      - service: script.jouer_sirene_boucle

  ### Scripts pour les deux automatisations du input_boolean ###
  sourdine_sirene:
    alias: "[Alarme] Mettre le son de la sirène en sourdine"
    sequence:
      - service: xiaomi.play_ringtone
        data_template:
          gw_mac: !secret xiaomi_gateway_mac
          ringtone_id: "{{ states.input_select.sirenes_gateway.state.split('-')[0] }}"
          ringtone_vol: "0"

  activer_son_sirene:
    alias: "[Alarme] Activer le son de la sirène"
    sequence:
      - service: xiaomi.play_ringtone
        data_template:
          gw_mac: !secret xiaomi_gateway_mac
          ringtone_id: "{{ states.input_select.sirenes_gateway.state.split('-')[0] }}"
          ringtone_vol: "{{ states.input_slider.gateway_volume.state|int }}"

###############################################################
# Automation
###############################################################
automation:
  ### Automatisations pour le input_boolean ###
  - alias: "[Alarme] Boolean Sirène en sourdine"
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_boolean.sourdine_sirenes_gateway
        to: "on"
    action:
      - service: xiaomi_aqara.stop_ringtone
        data:
          gw_mac: !secret xiaomi_gateway_mac
      - service: script.turn_on
        entity_id: script.sourdine_sirene

  - alias: "[Alarme] Boolean Sirène son activé"
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_boolean.sourdine_sirenes_gateway
        to: "off"
    action:
      - service: script.turn_on
        entity_id: script.activer_son_sirene

  ############### Armer ###############

  - alias: "Armer alarme"
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_entree_action
        to: "hold"
    condition:
      - condition: state
        entity_id: alarm_control_panel.maison
        state: disarmed
        for: "00:00:10"
      - condition: state
        entity_id: binary_sensor.xiaomi_door_contact
        attribute: contact
        state: false
    action:
      - service: light.turn_on
        data:
          entity_id: light.gateway_light_7811dcfaa3ee
          rgb_color: [255, 63, 0]
          brightness_pct: 100
      - service: notify.alexa_media_echo_salon
        data:
          message: Au revoir!
          data:
            type: announce
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.maison

  - alias: "Armer alarme (nuit)"
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_entree_couloir_action
        to: "single_both"
    condition:
      - condition: state
        entity_id: alarm_control_panel.maison
        state: disarmed
      - condition: state
        entity_id: binary_sensor.xiaomi_door_contact
        attribute: contact
        state: true
    action:
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.maison
      - delay:
          seconds: 1
      - service: light.turn_on
        data:
          entity_id: light.gateway_light_7811dcfaa3ee
          rgb_color: [0, 255, 255]
          brightness_pct: 25
      - delay:
          seconds: 5
      - service: light.toggle
        entity_id: light.sonoff_chambre

  - alias: "Armer alarme (nuit auto)"
    trigger:
      - platform: state
        entity_id: light.toutes_lumieres
        to: "off"
        for: "1:00:00"
    condition:
      - condition: state
        entity_id: alarm_control_panel.maison
        state: disarmed
      - condition: state
        entity_id: binary_sensor.xiaomi_door_contact
        attribute: contact
        state: true
      # - condition: time
      #   after: "20:00:00"
      #   before: "06:40:00"
      - condition: template
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'PowerOff') }}"
      - condition: numeric_state
        entity_id: sensor.tuya_ordi_power
        below: 40
    action:
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.maison

  - alias: "[Alarme] Armée"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.maison
        to: "armed_away"
    action:
      - service: light.turn_on
        data:
          entity_id: light.gateway_light_7811dcfaa3ee
          color_name: red
          brightness_pct: 100
      - service: notify.alexa_media
        data:
          target:
            - media_player.echo_salon
            - media_player.echo_cuisine
          message: Alarme activée
          data:
            type: announce
      - service: notify.mobile_app_iphone_de_le_gone
        alias: "Notification alarme armée"
        data:
          message: Tout est sous contrôle
          title: "Alarme armée"

  ############### Déclencher ###############

  - alias: "Déclencher alarme"
    trigger:
      - platform: state
        entity_id: binary_sensor.xiaomi_door_contact
        attribute: contact
        to: false
      - platform: state
        entity_id: binary_sensor.xiaomi_fenetre_sam_contact
        from: "off"
        to: "on"
      - platform: state
        entity_id: binary_sensor.xiaomi_fenetre_cuisine_contact
        from: "off"
        to: "on"
      - platform: state
        entity_id: binary_sensor.xiaomi_fenetre_sdb_contact
        from: "off"
        to: "on"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.maison
            state: armed_night
          - condition: state
            entity_id: alarm_control_panel.maison
            state: armed_away
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.maison
        data:
          code: !secret alarm_code
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret xiaomi_gateway_mac
          ringtone_id: 10
          ringtone_vol: 5
      - service: light.turn_on
        data:
          entity_id: light.gateway_light_7811dcfaa3ee
          color_name: red
          brightness_pct: 100
      - service: light.turn_on
        data:
          entity_id: light.sonoff_entree_1,light.sonoff_entree_2,light.sonoff_entree_3
      - service: timer.start
        data:
          entity_id: timer.entree

  - alias: "[Alarme] Déclenchée"
    initial_state: on
    trigger:
      platform: state
      entity_id: alarm_control_panel.maison
      to: "triggered"
    action:
      - service: notify.mobile_app_iphone_de_le_gone
        alias: "Notification alarme déclenchée"
        data:
          message: Déclenchement de la sirène
          title: "[Alarme] Déclenchée"
          data:
            push:
              interruption-level: critical
      - service: script.turn_on
        entity_id: script.jouer_sirene_boucle

  ############### Désarmer ###############

  - alias: "Désactiver alarme"
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_entree_action
        to: "hold"
      - platform: state
        entity_id: sensor.xiaomi_shoes_action
        to: "hold"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.maison
            state: armed_night
          - condition: state
            entity_id: alarm_control_panel.maison
            state: armed_away
          - condition: state
            entity_id: alarm_control_panel.maison
            state: pending
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.maison
        data:
          code: !secret alarm_code

  - alias: "Désactiver alarme nuit"
    trigger:
      - platform: state
        entity_id: light.toutes_lumieres
        to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.maison
        state: armed_night
      - condition: time
        after: "04:00:00"
        before: "20:00:00"
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.maison
        data:
          code: !secret alarm_code

  - alias: "[Alarme] Désactivée"
    trigger:
      platform: state
      entity_id: alarm_control_panel.maison
      to: "disarmed"
    action:
      - service: light.turn_off
        data:
          entity_id: light.gateway_light_7811dcfaa3ee

  - alias: "[Alarme away] Désactivée"
    trigger:
      platform: state
      entity_id: alarm_control_panel.maison
      from: "armed_away"
      to: "disarmed"
    action:
      - service: notify.mobile_app_iphone_de_le_gone
        alias: "Notification alarme déclenchée"
        data:
          message: Tout va bien
          title: "[Alarme] Désactivée"
      - service: notify.alexa_media
        data:
          target:
            - media_player.echo_salon
          message: Alarme désactivée. Bienvenu à la maison!
          data:
            type: announce
