

###############################################################
# Scripts
###############################################################
  
script:
  neato_cuisine:
    alias: Cuisine
    sequence:
    - service: vacuum.neato_custom_cleaning
      data:
        entity_id: vacuum.conchita
        mode: 1
        navigation: 2
        zone: "Cuisine"
  
  neato_chambre:
    alias: Chambre
    sequence:
    - service: vacuum.neato_custom_cleaning
      data:
        entity_id: vacuum.conchita
        mode: 1
        navigation: 2
        zone: "Chambre Principale"
  
  neato_sdb:
    alias: SdB
    sequence:
    - service: vacuum.neato_custom_cleaning
      data:
        entity_id: vacuum.conchita
        mode: 1
        navigation: 2
        zone: "Salle De Bains"
  
  neato_couloir:
    alias: Couloir
    sequence:
    - service: vacuum.neato_custom_cleaning
      data:
        entity_id: vacuum.conchita
        mode: 1
        navigation: 2
        zone: "Couloir"
  
  neato_cleo:
    alias: Cléo
    sequence:
    - service: vacuum.neato_custom_cleaning
      data:
        entity_id: vacuum.conchita
        mode: 1
        navigation: 2
        zone: "Chambre Cléo"
  
  neato_wc:
    alias: Toilettes
    sequence:
    - service: vacuum.neato_custom_cleaning
      data:
        entity_id: vacuum.conchita
        mode: 1
        navigation: 2
        zone: "Toilettes"
  
  neato_entree:
    alias: Entrée
    sequence:
    - service: vacuum.neato_custom_cleaning
      data:
        entity_id: vacuum.conchita
        mode: 1
        navigation: 2
        zone: "Entrée"
  
  neato_table:
    alias: Table
    sequence:
    - service: vacuum.neato_custom_cleaning
      data:
        entity_id: vacuum.conchita
        mode: 1
        navigation: 2
        zone: "Table"
  
  neato_sam:
    alias: SàM
    sequence:
    - service: vacuum.neato_custom_cleaning
      data:
        entity_id: vacuum.conchita
        mode: 1
        navigation: 2
        zone: "Salle a Manger"
  
  neato_table_basse:
    alias: Table basse
    sequence:
    - service: vacuum.neato_custom_cleaning
      data:
        entity_id: vacuum.conchita
        mode: 1
        navigation: 2
        zone: "Table basse"


###############################################################
# Automation
###############################################################

automation:

  - id: '1572943897953'
    alias: Conchita se decharge
    description: ''
    trigger:
    - entity_id: sensor.conchita_battery
      from: '1'
      platform: state
      to: '80'
    condition: []
    action:
    - service: notify.ios_iphone_de_le_gone
      data:
        data:
          push:
            badge: 5
            thread-id: home-assistant
        message: Quelqu'un pourrait la remettre sur sa base?
        title: Conchita se décharge anormalement
    - service: notify.alexa_media_echo_salon
      data:
        target: media_player.alexa
        message: Conchita se décharge anormalement. Quelqu'un pourrait la remettre sur
          sa base?
        data:
          type: announce
          method: all
  
  - id: '1572943972632'
    alias: Conchita en erreur
    description: ''
    trigger:
    - entity_id: vacuum.conchita
      from: error
      platform: state
    condition: []
    action:
    - service: notify.alexa_media_echo_salon
      data:
        target: media_player.alexa
        message: Conchita a un soucis, quelqu'un veut bien l'aider?
        data:
          type: announce
          method: all
          
  - alias: Aspirateur Salle à manger et salon
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_both_158d0003558c12
        click_type: long_both
    action:
    - service: script.neato_sam
      
  - alias: Aspirateur Cléo
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d0002f35399
        click_type: long
    action:
    - service: script.neato_cleo
      
  - alias: Aspirateur Parents
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d0002f31e64
        click_type: long
    action:
    - service: script.neato_chambre
      
  - alias: Aspirateur Cuisine
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d00031b5437
        click_type: long
    action:
    - service: script.neato_cuisine
  
  - alias: Aspirateur entrée
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d000355939d
        click_type: long
    action:
    - service: script.neato_entree
  
  - alias: Aspirateur couloir
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d000355939d
        click_type: long
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d00036d0507
        click_type: long
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d0003057c5b
        click_type: long
    action:
    - service: script.neato_couloir