###############################################################
# Scripts
###############################################################

script:
  neato_clean:
    mode: queued
    alias: Neato Room Cleaning
    max: 10
    fields:
      zone:
        name: Zone
        required: true
        example: "Cuisine"
        selector:
          select:
            options:
              - "Cuisine"
              - "Chambre Principale"
              - "Salle De Bains"
              - "Couloir"
              - "Chambre Cléo"
              - "Toilettes"
              - "Entree"
              - "Table"
              - "Salle a Manger"
              - "Table basse"
    sequence:
      - wait_template: "{{ is_state('vacuum.conchita', 'docked') }}"
        continue_on_timeout: false
        timeout: "00:20:00"
      - service: neato.custom_cleaning
        data:
          entity_id: vacuum.conchita
          mode: 1
          navigation: 2
          zone: "{{ zone }}"
      - wait_for_trigger:
          - platform: state
            entity_id: vacuum.conchita
            to: docked
        continue_on_timeout: false
        timeout: "00:20:00"

  neato_stop:
    alias: Stop aspirateur
    sequence:
      - service: vacuum.locate
        data:
          entity_id: vacuum.conchita
      - wait_template: "{{ state_attr('vacuum.conchita', 'status') != 'Eco Recovering Location' and state_attr('vacuum.conchita', 'status') != 'Charging' }}"
        timeout: "00:01:00"
        continue_on_timeout: false
      - service: vacuum.pause
        data:
          entity_id: vacuum.conchita
      - service: vacuum.return_to_base
        data:
          entity_id: vacuum.conchita

  neato_cuisine:
    alias: Cuisine
    sequence:
      - service: script.neato_clean
        data:
          zone: "Cuisine"

  neato_chambre:
    alias: Chambre
    sequence:
      - service: script.neato_clean
        data:
          zone: "Chambre Principale"

  neato_sdb:
    alias: SdB
    sequence:
      - service: script.neato_clean
        data:
          zone: "Salle De Bains"

  neato_couloir:
    alias: Couloir
    sequence:
      - service: script.neato_clean
        data:
          zone: "Couloir"

  neato_cleo:
    alias: Cléo
    sequence:
      - service: script.neato_clean
        data:
          zone: "Chambre Cléo"

  neato_wc:
    alias: Toilettes
    sequence:
      - service: script.neato_clean
        data:
          zone: "Toilettes"

  neato_entree:
    alias: Entrée
    sequence:
      - service: script.neato_clean
        data:
          zone: "Entree"

  neato_table:
    alias: Table
    sequence:
      - service: script.neato_clean
        data:
          zone: "Table"

  neato_sam:
    alias: SàM
    sequence:
      - service: script.neato_clean
        data:
          zone: "Salle a Manger"

  neato_table_basse:
    alias: Table basse
    sequence:
      - service: script.neato_clean
        data:
          zone: "Table basse"

###############################################################
# Automation
###############################################################

automation:
  ################### Programmation ###################

  - alias: Neato Cuisine (Programmation Ecole)
    triggers:
      - trigger: time
        at: "07:05:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: switch.conchita_schedule
        state: "on"
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: state
        entity_id: input_boolean.reveil_cleo
        state: "on"
    action:
      - action: notify.alexa_media_echo_salon
        data:
          message: Direction la salle de bain!
          data:
            type: announce
      - delay:
          minutes: "{{ 25 if is_state('input_boolean.reveil_cleo_tardif', 'on') else 0 | float }}"
      - action: script.neato_cuisine

  - alias: Neato Table basse (Programmation Ecole)
    trigger:
      platform: time
      at: "07:30:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: switch.conchita_schedule
        state: "on"
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: state
        entity_id: input_boolean.reveil_cleo
        state: "on"
    action:
      - action: notify.alexa_media_echo_salon
        data:
          message: Direction l'école!
          data:
            type: announce
      - delay:
          minutes: "{{ 35 if is_state('input_boolean.reveil_cleo_tardif', 'on') else 0 | float }}"
      - action: script.neato_table_basse

  - alias: Neato Entrée (Away)
    trigger:
      platform: time
      at: "11:00:00"
    condition:
      - condition: time
        weekday:
          - mon
          - wed
          - sat
          - sun
      - condition: state
        entity_id: switch.conchita_schedule
        state: "on"
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: state
        entity_id: alarm_control_panel.maison
        state: armed_away
    action:
      - action: script.neato_entree

  - alias: Neato Cuisine (Away)
    trigger:
      platform: time
      at: "11:20:00"
    condition:
      - condition: time
        weekday:
          - mon
          - wed
          - sat
          - sun
      - condition: state
        entity_id: switch.conchita_schedule
        state: "on"
      - condition: state
        entity_id: input_boolean.vacations
        state: "on"
      - condition: state
        entity_id: alarm_control_panel.maison
        state: armed_away
    action:
      - action: script.neato_cuisine

  - alias: Neato Table basse (Away)
    trigger:
      platform: time
      at: "11:40:00"
    condition:
      - condition: time
        weekday:
          - mon
          - wed
          - sat
          - sun
      - condition: state
        entity_id: switch.conchita_schedule
        state: "on"
      - condition: state
        entity_id: input_boolean.vacations
        state: "on"
      - condition: state
        entity_id: alarm_control_panel.maison
        state: armed_away
    action:
      - action: script.neato_table_basse

  - alias: Neato Couloir (Away)
    trigger:
      platform: time
      at: "16:20:00"
    condition:
      - condition: time
        weekday:
          - mon
          - wed
          - sat
          - sun
      - condition: state
        entity_id: switch.conchita_schedule
        state: "on"
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: state
        entity_id: alarm_control_panel.maison
        state: armed_away
    action:
      - action: script.neato_couloir
        enabled: false

  - alias: Neato Salle à Manger (Away)
    trigger:
      platform: time
      at: "16:40:00"
    condition:
      - condition: time
        weekday:
          - mon
          - wed
          - sat
          - sun
      - condition: state
        entity_id: switch.conchita_schedule
        state: "on"
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: state
        entity_id: alarm_control_panel.maison
        state: armed_away
    action:
      - action: script.neato_sam

  ################### Erreurs ###################

  - alias: Conchita se decharge
    trigger:
      - entity_id: sensor.conchita_battery
        from: "1"
        platform: state
        to: "80"
    condition:
      - condition: time
        after: "07:00:00"
        before: "20:00:00"
    action:
      - service: notify.mobile_app_iphone_amadeus
        data:
          push:
            interruption-level: time-sensitive
          message: Quelqu'un pourrait la remettre sur sa base?
          title: Conchita se décharge anormalement
      - service: notify.alexa_media_echo_salon
        data:
          message: Conchita se décharge anormalement. Quelqu'un pourrait la remettre sur sa base?
          data:
            type: announce

  - alias: Conchita en erreur
    trigger:
      - entity_id: vacuum.conchita
        to: error
        platform: state
        for: "00:10:00"
    condition:
      - condition: time
        after: "07:00:00"
        before: "20:00:00"
    action:
      - service: notify.alexa_media_echo_salon
        data:
          message: Conchita a un soucis, quelqu'un veut bien l'aider?
          data:
            type: announce

  - alias: Conchita offline
    trigger:
      - entity_id: vacuum.conchita
        to: unavailable
        platform: state
        for: "00:10:00"
    condition:
      - condition: time
        after: "07:00:00"
        before: "20:00:00"
    action:
      - service: notify.alexa_media_echo_salon
        data:
          message: Conchita est déconnectée, quelqu'un veut bien l'aider?
          data:
            type: announce

  - alias: Conchita laisse tomber
    trigger:
      - entity_id: vacuum.conchita
        to: error
        platform: state
        for: "00:02:00"
    condition: []
    action:
      - service: script.neato_stop

  ################### Boutons ###################

  - alias: Aspirateur Salle à manger et salon
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sam_action
        to: "hold_both"
    action:
      - service: script.neato_sam

  - alias: Aspirateur Cléo
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_cleo
        to: "hold"
    action:
      - service: script.neato_cleo

  - alias: Aspirateur Parents
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_bedroom_action
        to: "hold"
    action:
      - service: script.neato_chambre

  - alias: Aspirateur Cuisine
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_cuisine_action
        to: "hold"
    action:
      - service: script.neato_cuisine

  - alias: Aspirateur entrée
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_entree_couloir_action
        to: "hold_left"
    action:
      - service: script.neato_entree

  - alias: Aspirateur couloir
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_entree_couloir_action
        to: "hold_right"
      - platform: state
        entity_id: sensor.xiaomi_sdb_action
        to: "hold_right"
      - platform: state
        entity_id: sensor.xiaomi_couloir
        to: "hold"
    action:
      - service: script.neato_couloir
