###############################################################
# Scripts
###############################################################

script:
  neato_stop:
    alias: Stop aspirateur
    sequence:
      - service: vacuum.locate
        data:
          entity_id: vacuum.conchita
      - wait_template: "{{ state_attr('vacuum.conchita', 'status') != 'Eco Recovering Location' and state_attr('vacuum.conchita', 'status') != 'Charging' }}"
        timeout: "00:01:00"
        continue_on_timeout: false
      - service: vacuum.pause
        data:
          entity_id: vacuum.conchita
      - service: vacuum.return_to_base
        data:
          entity_id: vacuum.conchita

  neato_cuisine:
    alias: Cuisine
    sequence:
      - service: neato.custom_cleaning
        data:
          entity_id: vacuum.conchita
          mode: 1
          navigation: 2
          zone: "Cuisine"

  neato_chambre:
    alias: Chambre
    sequence:
      - service: neato.custom_cleaning
        data:
          entity_id: vacuum.conchita
          mode: 1
          navigation: 2
          zone: "Chambre Principale"

  neato_sdb:
    alias: SdB
    sequence:
      - service: neato.custom_cleaning
        data:
          entity_id: vacuum.conchita
          mode: 1
          navigation: 2
          zone: "Salle De Bains"

  neato_couloir:
    alias: Couloir
    sequence:
      - service: neato.custom_cleaning
        data:
          entity_id: vacuum.conchita
          mode: 1
          navigation: 2
          zone: "Couloir"

  neato_cleo:
    alias: Cléo
    sequence:
      - service: neato.custom_cleaning
        data:
          entity_id: vacuum.conchita
          mode: 1
          navigation: 2
          zone: "Chambre Cléo"

  neato_wc:
    alias: Toilettes
    sequence:
      - service: neato.custom_cleaning
        data:
          entity_id: vacuum.conchita
          mode: 1
          navigation: 2
          zone: "Toilettes"

  neato_entree:
    alias: Entrée
    sequence:
      - service: neato.custom_cleaning
        data:
          entity_id: vacuum.conchita
          mode: 1
          navigation: 2
          zone: "Entree"

  neato_table:
    alias: Table
    sequence:
      - service: neato.custom_cleaning
        data:
          entity_id: vacuum.conchita
          mode: 1
          navigation: 2
          zone: "Table"

  neato_sam:
    alias: SàM
    sequence:
      - service: neato.custom_cleaning
        data:
          entity_id: vacuum.conchita
          mode: 1
          navigation: 2
          zone: "Salle a Manger"

  neato_table_basse:
    alias: Table basse
    sequence:
      - service: neato.custom_cleaning
        data:
          entity_id: vacuum.conchita
          mode: 1
          navigation: 2
          zone: "Table basse"

###############################################################
# Automation
###############################################################

automation:
  ################### Programmation ###################

  - alias: Neato Cuisine (Programmation Ecole)
    trigger:
      platform: time
      at: "07:30:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - thu
          - fri
      - condition: state
        entity_id: switch.conchita_schedule
        state: "on"
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
    action:
      - service: script.neato_cuisine

  - alias: Neato Table basse (Programmation Ecole)
    trigger:
      platform: time
      at: "08:15:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - thu
          - fri
      - condition: state
        entity_id: switch.conchita_schedule
        state: "on"
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
    action:
      - service: script.neato_table_basse

  - alias: Neato Entrée (Programmation)
    trigger:
      platform: time
      at: "08:30:00"
    condition:
      - condition: time
        weekday:
          - tue
      - condition: state
        entity_id: switch.conchita_schedule
        state: "on"
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
    action:
      - service: script.neato_entree

  - alias: Neato Couloir (Programmation)
    trigger:
      platform: time
      at: "08:30:00"
    condition:
      - condition: time
        weekday:
          - thu
      - condition: state
        entity_id: switch.conchita_schedule
        state: "on"
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
    action:
      - service: script.neato_couloir

  ################### Erreurs ###################

  - id: "1572943897953"
    alias: Conchita se decharge
    description: ""
    trigger:
      - entity_id: sensor.conchita_battery
        from: "1"
        platform: state
        to: "80"
    condition: []
    action:
      - service: notify.mobile_app_iphone_de_le_gone
        data:
          data:
            push:
              badge: 5
              thread-id: home-assistant
          message: Quelqu'un pourrait la remettre sur sa base?
          title: Conchita se décharge anormalement
      - service: notify.alexa_media_echo_salon
        data:
          message: Conchita se décharge anormalement. Quelqu'un pourrait la remettre sur sa base?
          data:
            type: announce

  - id: "1572943972632"
    alias: Conchita en erreur
    description: ""
    trigger:
      - entity_id: vacuum.conchita
        to: error
        platform: state
        for: "00:10:00"
    condition: []
    action:
      - service: notify.alexa_media_echo_salon
        data:
          message: Conchita a un soucis, quelqu'un veut bien l'aider?
          data:
            type: announce

  ################### Boutons ###################

  - alias: Aspirateur Salle à manger et salon
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sam_action
        to: "hold_both"
    action:
      - service: script.neato_sam

  - alias: Aspirateur Cléo
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_cleo
        to: "hold"
    action:
      - service: script.neato_cleo

  - alias: Aspirateur Parents
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_bedroom_action
        to: "hold"
    action:
      - service: script.neato_chambre

  - alias: Aspirateur Cuisine
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_cuisine_action
        to: "hold"
    action:
      - service: script.neato_cuisine

  - alias: Aspirateur entrée
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_shoes_action
        to: "hold"
      - platform: state
        entity_id: sensor.xiaomi_entree_couloir_action
        to: "hold_left"
    action:
      - service: script.neato_entree

  - alias: Aspirateur couloir
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_entree_couloir_action
        to: "hold_right"
      - platform: state
        entity_id: sensor.xiaomi_sdb_action
        to: "hold_right"
      - platform: state
        entity_id: sensor.xiaomi_couloir
        to: "hold"
    action:
      - service: script.neato_couloir
