###############################################################
# Scripts
###############################################################

script:
  roborock_clean:
    mode: queued
    alias: Roborock Room Cleaning
    max: 10
    fields:
      mop:
        description: Run mop step after vacuum
        selector:
          boolean:
      turbo:
        description: Run fan speed at max speed
        selector:
          boolean:
      rooms:
        description: Room IDs to clean
        selector:
          select:
            multiple: true
            options:
              - "1"
              - "2"
              - "3"
              - "4"
              - "5"
              - "6"
              - "7"
              - "8"
    sequence:
      - wait_template: "{{ is_state('vacuum.medor', 'docked') }}"
        continue_on_timeout: false
        timeout: "00:20:00"
      - action: select.select_option
        target:
          entity_id: select.medor_mop_intensity
        data:
          option: "off"
      - if:
          - condition: template
            value_template: "{{ mop | default(false) }}"
        then:
          - action: select.select_option
            target:
              entity_id: select.medor_mop_intensity
            data:
              option: "medium"
      - if:
          - condition: template
            value_template: "{{ turbo | default(false) }}"
        then:
          - action: vacuum.set_fan_speed
            target:
              entity_id: vacuum.medor
            data:
              fan_speed: max_plus
        else:
          - action: vacuum.set_fan_speed
            target:
              entity_id: vacuum.medor
            data:
              fan_speed: balanced

      - delay: "00:00:10"
      - action: vacuum.send_command
        target:
          entity_id: vacuum.medor
        data:
          command: app_segment_clean
          params:
            - segments: "{{ rooms | map('int') | list }}"
              repeat: 2
      - delay: "00:00:10"
      - wait_template: "{{ is_state('vacuum.medor', 'docked') }}"
        continue_on_timeout: false
        timeout: "00:20:00"

  roborock_aspirer_cuisine:
    alias: Aspirer Cuisine
    sequence:
      - action: script.roborock_clean
        data:
          mop: false
          rooms: "2"

  roborock_aspirer_chambre:
    alias: Aspirer Chambre
    sequence:
      - action: script.roborock_clean
        data:
          mop: false
          rooms: "7"

  roborock_aspirer_sdb:
    alias: Aspirer SdB
    sequence:
      - action: script.roborock_clean
        data:
          mop: false
          rooms: "6"

  roborock_aspirer_couloir:
    alias: Aspirer Couloir
    sequence:
      - action: script.roborock_clean
        data:
          mop: false
          rooms: "5"

  roborock_aspirer_cleo:
    alias: Aspirer Cléo
    sequence:
      - action: script.roborock_clean
        data:
          mop: false
          rooms: "4"

  roborock_aspirer_wc:
    alias: Aspirer Toilettes
    sequence:
      - action: script.roborock_clean
        data:
          turbo: true
          mop: false
          rooms: "1"

  roborock_aspirer_entree:
    alias: Aspirer Entrée
    sequence:
      - action: script.roborock_clean
        data:
          mop: false
          rooms: "8"

  roborock_aspirer_sam:
    alias: Aspirer SàM
    sequence:
      - action: script.roborock_clean
        data:
          mop: false
          rooms: "3"

  roborock_laver_cuisine:
    alias: Laver Cuisine
    sequence:
      - action: script.roborock_clean
        data:
          mop: true
          rooms: "2"

  roborock_laver_chambre:
    alias: Laver Chambre
    sequence:
      - action: script.roborock_clean
        data:
          mop: true
          rooms: "7"

  roborock_laver_sdb:
    alias: Laver SdB
    sequence:
      - action: script.roborock_clean
        data:
          mop: true
          rooms: "6"

  roborock_laver_couloir:
    alias: Laver Couloir
    sequence:
      - action: script.roborock_clean
        data:
          mop: true
          rooms: "5"

  roborock_laver_cleo:
    alias: Laver Cléo
    sequence:
      - action: script.roborock_clean
        data:
          mop: true
          rooms: "4"

  roborock_laver_wc:
    alias: Laver Toilettes
    sequence:
      - action: script.roborock_clean
        data:
          mop: true
          rooms: "1"

  roborock_laver_entree:
    alias: Laver Entrée
    sequence:
      - action: script.roborock_clean
        data:
          mop: true
          rooms: "8"

  roborock_laver_sam:
    alias: Laver SàM
    sequence:
      - action: script.roborock_clean
        data:
          mop: true
          rooms: "3"

  roborock_laver_table_basse:
    alias: Laver Table basse
    sequence:
      - action: vacuum.send_command
        target:
          entity_id: vacuum.medor
        data:
          command: app_zoned_clean
          params: [[29033, 31557, 30953, 34808]]

###############################################################
# Automation
###############################################################

automation:
  ################### Programmation ###################

  - alias: Roborock entree
    triggers:
      - trigger: time
        at: "10:00:00"
      - trigger: time
        at: "16:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: state
        entity_id: input_boolean.reveil_cleo
        state: "on"
    action:
      - action: script.roborock_aspirer_entree

  - alias: Roborock Cuisine (Programmation Ecole)
    triggers:
      - trigger: time
        at: "07:05:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri

      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: state
        entity_id: input_boolean.reveil_cleo
        state: "on"
    action:
      - action: notify.send_message
        data:
          message: Direction la salle de bain!
        target:
          entity_id: notify.echo_salon_announce
      - delay:
          minutes: "{{ 60 if is_state('input_boolean.reveil_cleo_tardif', 'on') else 0 | float }}"
      - action: script.roborock_aspirer_cuisine

  - alias: Roborock (Away)
    triggers:
      - trigger: time
        at: "11:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: state
        entity_id: alarm_control_panel.maison
        state: armed_away
    action:
      - action: script.roborock_clean
        data:
          mop: false
          rooms:
            - "2"
            - "3"
            - "8"
            - "1"
            - "5"
            - "6"
      - action: script.roborock_clean
        data:
          mop: true
          rooms:
            - "2"
            - "3"
            - "8"
            - "1"
            - "5"
            - "6"

  ################### Boutons ###################

  - alias: Aspirateur Salle à manger et salon
    triggers:
      - trigger: state
        entity_id: sensor.xiaomi_sam_action
        to: "hold_both"
    action:
      - action: script.roborock_laver_sam

  - alias: Aspirateur Cléo
    triggers:
      - trigger: state
        entity_id: sensor.xiaomi_cleo_action
        to: "hold"
    action:
      - action: script.roborock_laver_cleo

  - alias: Aspirateur Parents
    triggers:
      - trigger: state
        entity_id: sensor.xiaomi_bedroom_action
        to: "hold"
    action:
      - action: script.roborock_laver_chambre

  - alias: Aspirateur Cuisine
    triggers:
      - trigger: state
        entity_id: sensor.xiaomi_cuisine_action
        to: "hold"
    action:
      - action: script.roborock_laver_cuisine

  - alias: Aspirateur entrée
    triggers:
      - trigger: state
        entity_id: sensor.xiaomi_entree_couloir_action
        to: "hold_left"
    action:
      - action: script.roborock_aspirer_entree

  - alias: Aspirateur couloir
    triggers:
      - trigger: state
        entity_id: sensor.xiaomi_entree_couloir_action
        to: "hold_right"
      - trigger: state
        entity_id: sensor.xiaomi_sdb_action
        to: "hold_right"
      - trigger: state
        entity_id: sensor.xiaomi_couloir_action
        to: "hold"
    action:
      - action: script.roborock_laver_couloir
