
###############################################################
# Automation
###############################################################
automation:

  - alias: Humidité SdB
    description: "Humidité SdB"
    trigger:
    - entity_id: sensor.humidity_158d0004465b49
      above: 90
      platform: numeric_state
      for:
        minutes: 30
    - entity_id: sensor.humidity_158d0004465b49
      above: 80
      platform: numeric_state
      for:
        minutes: 60
    condition: []
    action:
    - service: notify.mobile_app_iphone_de_le_gone
      data:
        data:
          push:
            badge: 5
            thread-id: home-assistant
        message: Quelqu'un pourrait ouvrir la fenêtre?
        title: Il y a trop d'humidité dans la Salle de Bain
    - service: notify.alexa_media_echo_salon
      data:
        target: media_player.alexa
        message:
          Il y a trop d'humidité dans la Salle de Bain. Quelqu'un pourrait ouvrir la fenêtre?
        data:
          type: announce
          method: all







  - alias: Chauffage SdB On
    trigger:
    - entity_id: light.salle_de_bain
      platform: state
      from: 'off'
      to: 'on'
    condition:
    - condition: time
      after: '07:00:00'
      before: '11:00:00'
    - condition: numeric_state
      entity_id: sensor.temperature_158d0004465b49
      below: 25
    action:
    - service: light.turn_on
      entity_id: light.s20

  - alias: Chauffage SdB Toggle
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d00036d0507
        click_type: long
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d00036d0507
        click_type: double
    action:
    - service: light.toggle
      entity_id: light.s20
      
  - alias: Chauffage SdB Off
    trigger:
    - entity_id: light.salle_de_bain
      platform: state
      to: 'off'
    - platform: numeric_state
      entity_id: sensor.temperature_158d0004465b49
      above: 25
    action:
    - service: light.turn_off
      entity_id: light.s20
      