###############################################################
# Automation
###############################################################
automation:
  - alias: Appel Cleo
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_cleo_up_action
        to: "hold"
    action:
      - service: notify.mobile_app_iphone_amadeus
        data:
          push:
            interruption-level: time-sensitive
          message: Appel passé depuis son lit
          title: Cléo aimerait passer un message
      - service: notify.alexa_media
        data:
          message: Cléo aimerait passer un message
          target:
            - media_player.echo_de_cleo
            - media_player.echo_salon
          data:
            type: announce
