###############################################################
# Inputs
###############################################################

input_boolean:
  vacations:
    name: Is it a day off
    icon: mdi:calendar-remove

  reveil_cleo_tardif:
    name: Réveil tardif Cléo (collège à 9h)
    icon: mdi:alarm-snooze

  reveil_cleo:
    name: Reveil Cléo
    icon: mdi:alarm

###############################################################
# Sensor
###############################################################

sensor:
  - platform: rest
    scan_interval: "01:00:00"
    name: Saint du jour
    resource_template: http://domogeek.entropialux.com/feastedsaint/now/1-3

###############################################################
# Script
###############################################################

script:
  lavage_dents:
    alias: Lavage dents
    sequence:
      - parallel:
          # Salon
          - action: alexa_devices.send_sound
            data:
              device_id: 469a2e22fa36880f8ba14e1fadd9d995
              sound: air_horn_03
          # Cuisine
          - action: alexa_devices.send_sound
            data:
              device_id: da05d4e93809561b0b1b7e9dbe2ea3b5
              sound: air_horn_03
          # Cleo
          - action: alexa_devices.send_sound
            data:
              device_id: 36b1082749eeef5cd31d83fde1dfa777
              sound: air_horn_03
  switch_reveil:
    alias: Switch reveil
    sequence:
      - service: input_boolean.toggle
        target:
          entity_id: input_boolean.reveil_cleo

###############################################################
# Automation
###############################################################

automation:
  - alias: Météo du jour
    trigger:
      platform: time
      at: "06:55:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: state
        entity_id: input_boolean.reveil_cleo
        state: "on"
    action:
      - delay:
          minutes: "{{ 60 if is_state('input_boolean.reveil_cleo_tardif', 'on') else 0 | int }}"
      - action: notify.send_message
        data:
          message:
            Bonjour! Aujourd'hui, c'est {{ states("sensor.nice_cloud_cover") }} % de nuages et
            un indice UV de {{ states("sensor.nice_uv") }}. Comptez
            {{ states("sensor.nice_rain_chance") }} % de chances pour qu'il pleuve.
            Il fait {{ state_attr("weather.nice", "temperature") }}
            degrés dehors avec {{ state_attr("weather.nice", "wind_speed") }} km/h de vent. Bonne journée!
        target:
          entity_id: notify.echo_salon_speak

  - alias: Réveil Cléo
    description: ""
    trigger:
      platform: time
      at: "06:45:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: state
        entity_id: input_boolean.reveil_cleo
        state: "on"
    action:
      - delay:
          minutes: "{{ 60 if is_state('input_boolean.reveil_cleo_tardif', 'on') else 0 | int }}"
      - action: notify.send_message
        target:
          entity_id:
            - notify.echo_de_cleo_announce
        data:
          message: >
            {% set months = ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"] %}
            {% set days = ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"]  %}
            Bonjour! Aujourd'hui, nous sommes le {{ days[now().weekday()] + ' ' + (now().day | string) + ' ' + months[now().month-1] }}.
            Le saint du jour est {{ states("sensor.saint_du_jour") }}. Bonne journée!
      - action: alexa_devices.send_text_command
        data:
          device_id: 36b1082749eeef5cd31d83fde1dfa777
          text_command: "Quel est l animal du jour"
