###############################################################
# Inputs
###############################################################

input_boolean:
  vacations:
    name: Is it a day off
    icon: mdi:calendar-remove

###############################################################
# Sensor
###############################################################

sensor:
  - platform: rest
    scan_interval: "01:00:00"
    name: Saint du jour
    resource_template: http://domogeek.entropialux.com/feastedsaint/now/1-3

###############################################################
# Automation
###############################################################

automation:
  - alias: Météo du jour
    trigger:
      platform: time
      at: "07:00:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
    action:
      - service: notify.alexa_media_echo_salon
        data:
          message:
            Bonjour! Aujourd'hui, c'est {{ states("sensor.nice_cloud_cover") }} % de nuages et
            un indice UV de {{ states("sensor.nice_uv") }}. Comptez
            {{ states("sensor.nice_rain_chance") }} % de chances pour qu'il pleuve.
            Il fait {{ state_attr("weather.nice", "temperature") }}
            degrés dehors avec {{ state_attr("weather.nice", "wind_speed") }} km/h de vent. Bonne journée!
          data:
            type: announce

  - alias: Réveil Cléo
    description: ""
    trigger:
      platform: time
      at: "07:15:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
    action:
      - service: notify.alexa_media_echo_de_cleo
        data_template:
          message: >
            {% set months = ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"] %}
            {% set days = ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"]  %}
            Bonjour! Aujourd'hui, nous sommes le {{ days[now().weekday()] + ' ' + (now().day | string) + ' ' + months[now().month-1] }}.
            Le saint du jour est {{ states("sensor.saint_du_jour") }}. Bonne journée!
          data:
            type: announce

      - service: media_player.play_media
        data:
          entity_id: media_player.echo_de_cleo
          media_content_id: "Quel est l animal du jour"
          media_content_type: custom
