###############################################################
# Sensor
###############################################################

#sensor:
#  - platform: spotify-playlist-sensor
#    client_id: !secret spotify_playlist_sensor_clientid
#    client_secret: !secret spotify_playlist_sensor_secret

###############################################################
# Media players
###############################################################

media_player:
  - platform: yamaha
    name: rx_v475
    host: 192.168.1.75
    source_ignore:
      - "AV3"
      - "AV5"
      - "AV6"
      - "HDMI4"
      - "HDMI5"
      - "USB"
      - "V-AUX"
      - "iPod (USB)"
    source_names:
      AUDIO: "Wii"
      AV1: "AV1"
      AV2: "CD"
      AV4: "Sony TV"
      HDMI1: "PS3"
      HDMI2: "Box"
      HDMI3: "Plex"

###############################################################
# Scripts
###############################################################

script:
  sleep_mac:
    alias: Sleep Mac
    sequence:
      - action: shell_command.sleep_mac

  bt_mac:
    alias: Bluetooth Mac
    sequence:
      - action: shell_command.bt_mac

  volume_up:
    alias: Volume Up
    sequence:
      - action: media_player.volume_set
        entity_id: media_player.rx_v475
        data_template:
          volume_level: "{{ states.media_player.rx_v475.attributes.volume_level + 0.02 }}"

  volume_down:
    alias: Volume Down
    sequence:
      - action: media_player.volume_set
        entity_id: media_player.rx_v475
        data_template:
          volume_level: "{{ states.media_player.rx_v475.attributes.volume_level - 0.02 }}"

  activity_wii:
    alias: Wii
    sequence:
      - action: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - action: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - action: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AUDIO
      - action: shell_command.switch_tv_component

  activity_ps3:
    alias: PS3
    sequence:
      - action: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - action: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - action: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: HDMI1
      - action: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"

  activity_switch:
    alias: Switch
    sequence:
      - action: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - action: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - action: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: HDMI1
      - action: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"

  activity_netflix:
    alias: Netflix
    sequence:
      - action: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - action: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - action: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AV4
      - action: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"
      - action: shell_command.switch_tv_netflix

  activity_amazon:
    alias: Prime Video
    sequence:
      - action: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - action: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - action: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AV4
      - action: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"
      - action: shell_command.switch_tv_home
      - action: shell_command.switch_tv_home
      - action: shell_command.switch_tv_right
      - action: shell_command.switch_tv_confirm

  activity_play_tv:
    alias: Play TV
    sequence:
      - action: shell_command.switch_tv_play

  activity_pause_tv:
    alias: Pause TV
    sequence:
      - action: shell_command.switch_tv_pause
      - action: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AV1
      - action: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AV4

  activity_youtube:
    alias: Youtube
    sequence:
      - action: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - action: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - action: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AV4
      - action: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"
      - action: shell_command.switch_tv_youtube

  activity_youtube_kids:
    alias: Youtube Kids
    sequence:
      - action: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - action: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - action: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AV4
      - action: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"
      - action: shell_command.switch_tv_home
      - action: shell_command.switch_tv_home
      - action: shell_command.switch_tv_right
      - action: shell_command.switch_tv_right
      - action: shell_command.switch_tv_right
      - action: shell_command.switch_tv_right
      - action: shell_command.switch_tv_confirm

  activity_box:
    alias: Box
    sequence:
      - action: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - action: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - action: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: HDMI2
      - action: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"

  activity_plex:
    alias: Plex
    sequence:
      - action: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - action: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - action: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: HDMI3
      - action: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"

  activity_airplay:
    alias: Airplay
    sequence:
      - action: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - action: media_player.turn_off
        data:
          entity_id: media_player.sony_bravia_tv
      - action: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AirPlay

  activity_spotify:
    alias: Spotify
    sequence:
      - action: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - action: media_player.turn_off
        data:
          entity_id: media_player.sony_bravia_tv
      - action: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: Spotify

  activity_dlna:
    alias: iTunes
    sequence:
      - action: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - action: media_player.turn_off
        data:
          entity_id: media_player.sony_bravia_tv
      - action: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: SERVER

  activity_off:
    alias: "Off"
    sequence:
      - action: media_player.turn_off
        data:
          entity_id: media_player.sony_bravia_tv
      - delay: "00:00:03"
      - action: media_player.turn_off
        data:
          entity_id: media_player.rx_v475

###############################################################
# Automation
###############################################################

automation:
  # - alias: Eteindre AppleTV
  #   trigger:
  #     - trigger: state
  #       entity_id: media_player.sony_bravia_tv
  #       to: "offonoff"
  #   condition:
  #     - condition: template
  #       value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'AppleTV') }}"
  #   action:
  #     - action: remote.turn_on
  #       data:
  #         entity_id: remote.harmony_hub
  #         activity: "PowerOff"
  #     - action: remote.turn_off
  #       data:
  #         entity_id: remote.appletv

  - alias: Allumer AppleTV sans Harmony
    trigger:
      - trigger: state
        entity_id: media_player.appletv
        to: "idle"
      - trigger: state
        entity_id: media_player.appletv
        to: "paused"
    condition:
      - condition: state
        entity_id: switch.appletv
        state: "off"
        for:
          seconds: 20
      - condition: state
        entity_id: switch.tuya_tv
        state: "on"
        for:
          minutes: 1
    action:
      - action: switch.turn_on
        target:
          entity_id: switch.appletv

  - alias: Allumage initial Home Cinema
    trigger:
      - trigger: state
        entity_id: switch.tuya_tv
        from: "off"
        to: "on"
    action:
      - action: switch.turn_on
        target:
          entity_id: switch.appletv
      - delay: "00:00:10"
      - action: remote.send_command
        target:
          entity_id: remote.harmony_hub
        data:
          command: PowerOn
          device: 71869520
      - delay: "00:00:10"
      - action: remote.send_command
        target:
          entity_id: remote.harmony_hub
        data:
          command: PowerToggle
          device: 71869520

  # - alias: Eteindre AppleTV (boot)
  #   trigger:
  #     - trigger: state
  #       entity_id: media_player.appletv
  #       to: "idle"
  #   condition:
  #     condition: not
  #     conditions:
  #       - condition: state
  #         entity_id: switch.tuya_tv
  #         state: "on"
  #         for:
  #           minutes: 1
  #   action:
  #     - action: media_player.turn_off
  #       target:
  #         entity_id: media_player.appletv

  - alias: Eteindre AppleTV sans Harmony
    trigger:
      - trigger: state
        entity_id: media_player.appletv
        to: "standby"
      - trigger: state
        entity_id: media_player.appletv
        to: "off"
    condition:
      - condition: state
        entity_id: switch.appletv
        state: "on"
        for:
          seconds: 20
    action:
      - action: switch.turn_off
        target:
          entity_id: switch.appletv

  - alias: Eteindre AppleTV si Harmony Off
    trigger:
      - trigger: state
        entity_id: switch.appletv
        to: "off"
        for: "00:00:05"
    condition:
      - condition: state
        entity_id: media_player.appletv
        state: "idle"
    action:
      - action: media_player.turn_off
        target:
          entity_id: media_player.appletv

  # - alias: Eteindre AppleTV apres Harmony
  #   trigger:
  #     - trigger: state
  #       entity_id: select.harmony_hub_activities
  #       to: "off"
  #       for: "00:00:15"
  #   condition:
  #     - condition: state
  #       entity_id: media_player.appletv
  #       state: "on"
  #   action:
  #     - action: remote.turn_off
  #       data:
  #         entity_id: remote.appletv

  - alias: Eteindre Home Cinéma
    trigger:
      - trigger: state
        entity_id: sensor.xiaomi_sam_action
        to: "hold_right"
    action:
      - action: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "PowerOff"
      - action: light.turn_off
        entity_id: light.sonoff_salon
      - action: switch.turn_off
        entity_id: switch.tuya_tv

  - alias: Switch Home Cinéma
    trigger:
      - trigger: state
        entity_id: sensor.xiaomi_sam_action
        to: "double_right"
    action:
      - entity_id: switch.tuya_tv
        action: switch.toggle

  # - alias: TV ready
  #   trigger:
  #     - trigger: state
  #       entity_id: media_player.sony_bravia_tv
  #       to: "on"
  #   condition:
  #     - condition: template
  #       value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'PowerOff') }}"
  #   action:
  #     - action: media_player.turn_off
  #       target:
  #         entity_id: media_player.sony_bravia_tv
  #     - delay: "00:00:05"
  #     - action: media_player.play_media
  #       target:
  #         entity_id: media_player.echo_salon
  #       data:
  #         media_content_type: sound
  #         #          media_content_id: amzn_sfx_rooster_crow_01
  #         media_content_id: amzn_sfx_cat_meow_1x_01

  - alias: Son Netflix
    triggers:
      - trigger: template
        value_template: "{{ state_attr('media_player.rx_v475','source')  }}"
    condition:
      - condition: state
        entity_id: media_player.tele
        state: "on"
      - condition: state
        entity_id: media_player.rx_v475
        state: "on"
      - condition: template
        value_template: '{{ state_attr("media_player.rx_v475", "source") == "AV1" }}'
      - condition: template
        value_template: '{{ state_attr("media_player.sony_bravia_tv", "source") == "HDMI 3/ARC" }}'
    action:
      - action: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AV4

  - alias: Eteindre Mac
    trigger:
      - trigger: state
        entity_id: sensor.xiaomi_sam_action
        to: "hold_left"
    action:
      - action: script.sleep_mac
      - action: light.toggle
        entity_id: light.sonoff_sam

  - alias: Yamaha allumé par erreur
    trigger:
      - entity_id: media_player.rx_v475
        trigger: state
        to: "on"
    condition:
      - condition: template
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'PowerOff') }}"
    action:
      - action: media_player.turn_off
        data:
          entity_id: media_player.rx_v475

  - alias: TV allumée par erreur
    trigger:
      - trigger: template
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'PowerOff') }}"
        for: "00:00:10"
    condition:
      - condition: state
        entity_id: media_player.sony_bravia_tv
        state: "on"
    action:
      - action: remote.send_command
        target:
          entity_id: remote.harmony_hub
        data:
          command: PowerOff
          device: 71869520

  - alias: Sortir maison (HiFi)
    trigger:
      - trigger: state
        entity_id: alarm_control_panel.maison
        to: "armed_away"
      - trigger: state
        entity_id: alarm_control_panel.maison
        to: "armed_night"
    action:
      - action: switch.turn_off
        entity_id: switch.tuya_ordi
      - action: script.sleep_mac
      - action: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "PowerOff"

  - alias: TV pas sur Box
    trigger:
      - trigger: template
        value_template: "{{ is_state_attr('media_player.rx_v475','source','Box') }}"
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: media_player.sony_bravia_tv
          state: "HDMI 3/ARC"
          attribute: source
    action:
      - action: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"

  - alias: TV pas sur Switch
    trigger:
      - trigger: template
        value_template: "{{ is_state_attr('media_player.rx_v475','source','PS3') }}"
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: media_player.sony_bravia_tv
          state: "HDMI 3/ARC"
          attribute: source
    action:
      - action: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"
  # - alias: Playlist on Spotify
  #   trigger:
  #     - trigger: state
  #       entity_id: sensor.xiaomi_nawak
  #       to: "hold"
  #   action:
  #     - action: media_player.play_media
  #       data:
  #         entity_id: media_player.echo_salon
  #         media_content_id: Playlist Best of
  #         media_content_type: SPOTIFY

  - alias: Switch TV chambre
    trigger:
      - trigger: state
        entity_id: sensor.xiaomi_sdb_action
        to: "double_right"
    action:
      - action: switch.toggle
        entity_id: switch.osram_tv_chambre
