###############################################################
# Spotify
###############################################################

spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_secret

###############################################################
# Sensor
###############################################################

#sensor:
#  - platform: spotify-playlist-sensor
#    client_id: !secret spotify_playlist_sensor_clientid
#    client_secret: !secret spotify_playlist_sensor_secret

###############################################################
# Media players
###############################################################

media_player:
  - platform: yamaha
    name: rx_v475
    host: 192.168.0.75
    source_ignore:
      - "AV3"
      - "AV5"
      - "AV6"
      - "HDMI4"
      - "HDMI5"
      - "USB"
      - "V-AUX"
      - "iPod (USB)"
    source_names:
      AUDIO: "Wii"
      AV1: "AV1"
      AV2: "CD"
      AV4: "Sony TV"
      HDMI1: "PS3"
      HDMI2: "Box"
      HDMI3: "Plex"
  - platform: braviatv
    host: 192.168.1.65

###############################################################
# Scripts
###############################################################

script:
  sleep_mac:
    alias: Sleep Mac
    sequence:
      - service: shell_command.sleep_mac

  bt_mac:
    alias: Bluetooth Mac
    sequence:
      - service: shell_command.bt_mac

  volume_up:
    alias: Volume Up
    sequence:
      - service: media_player.volume_set
        entity_id: media_player.rx_v475
        data_template:
          volume_level: "{{ states.media_player.rx_v475.attributes.volume_level + 0.02 }}"

  volume_down:
    alias: Volume Down
    sequence:
      - service: media_player.volume_set
        entity_id: media_player.rx_v475
        data_template:
          volume_level: "{{ states.media_player.rx_v475.attributes.volume_level - 0.02 }}"

  activity_wii:
    alias: Wii
    sequence:
      - service: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - service: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AUDIO
      - service: shell_command.switch_tv_component

  activity_ps3:
    alias: PS3
    sequence:
      - service: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - service: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: HDMI1
      - service: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"

  activity_switch:
    alias: Switch
    sequence:
      - service: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - service: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: HDMI1
      - service: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"

  activity_netflix:
    alias: Netflix
    sequence:
      - service: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - service: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AV4
      - service: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"
      - service: shell_command.switch_tv_netflix

  activity_amazon:
    alias: Prime Video
    sequence:
      - service: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - service: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AV4
      - service: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"
      - service: shell_command.switch_tv_home
      - service: shell_command.switch_tv_home
      - service: shell_command.switch_tv_right
      - service: shell_command.switch_tv_confirm

  activity_play_tv:
    alias: Play TV
    sequence:
      - service: shell_command.switch_tv_play

  activity_pause_tv:
    alias: Pause TV
    sequence:
      - service: shell_command.switch_tv_pause
      - service: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AV1
      - service: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AV4

  activity_youtube:
    alias: Youtube
    sequence:
      - service: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - service: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AV4
      - service: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"
      - service: shell_command.switch_tv_youtube

  activity_youtube_kids:
    alias: Youtube Kids
    sequence:
      - service: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - service: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AV4
      - service: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"
      - service: shell_command.switch_tv_home
      - service: shell_command.switch_tv_home
      - service: shell_command.switch_tv_right
      - service: shell_command.switch_tv_right
      - service: shell_command.switch_tv_right
      - service: shell_command.switch_tv_right
      - service: shell_command.switch_tv_confirm

  activity_box:
    alias: Box
    sequence:
      - service: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - service: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: HDMI2
      - service: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"

  activity_plex:
    alias: Plex
    sequence:
      - service: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - service: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: HDMI3
      - service: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"

  activity_airplay:
    alias: Airplay
    sequence:
      - service: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - service: media_player.turn_off
        data:
          entity_id: media_player.sony_bravia_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AirPlay

  activity_spotify:
    alias: Spotify
    sequence:
      - service: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - service: media_player.turn_off
        data:
          entity_id: media_player.sony_bravia_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: Spotify

  activity_dlna:
    alias: iTunes
    sequence:
      - service: media_player.turn_on
        data:
          entity_id: media_player.rx_v475
      - service: media_player.turn_off
        data:
          entity_id: media_player.sony_bravia_tv
      - service: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: SERVER

  activity_off:
    alias: "Off"
    sequence:
      - service: media_player.turn_off
        data:
          entity_id: media_player.sony_bravia_tv
      - delay: "00:00:03"
      - service: media_player.turn_off
        data:
          entity_id: media_player.rx_v475

###############################################################
# Automation
###############################################################

automation:
  - alias: Eteindre Home Cinéma
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sam_action
        to: "hold_right"
    action:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "PowerOff"
      - service: light.toggle
        entity_id: light.sonoff_salon

  - alias: Son Netflix
    trigger:
      platform: template
      value_template: "{{ state_attr('media_player.rx_v475','source')  }}"
    condition:
      - condition: state
        entity_id: media_player.tele
        state: "on"
      - condition: state
        entity_id: media_player.rx_v475
        state: "on"
      - condition: template
        value_template: '{{ state_attr("media_player.rx_v475", "source") == "AV1" }}'
      - condition: template
        value_template: '{{ state_attr("media_player.sony_bravia_tv", "source") == "HDMI 3/ARC" }}'
    action:
      - service: media_player.select_source
        data:
          entity_id: media_player.rx_v475
          source: AV4

  - alias: Eteindre Mac
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sam_action
        to: "hold_left"
    action:
      - service: script.sleep_mac
      - service: light.toggle
        entity_id: light.sonoff_sam

  - alias: Yamaha allumé par erreur
    trigger:
      - entity_id: media_player.rx_v475
        from: "off"
        platform: state
        to: "on"
    condition:
      - condition: time
        after: "22:00:00"
        before: "06:00:00"
      - condition: state
        entity_id: media_player.tele
        state: "off"
    action:
      - service: media_player.turn_off
        data:
          entity_id: media_player.rx_v475

  - alias: Sortir maison (HiFi)
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_entree_action
        to: "hold"
    condition:
      - condition: state
        entity_id: alarm_control_panel.maison
        state: disarmed
    action:
      - service: script.sleep_mac
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: "PowerOff"
      - service: notify.alexa_media_echo_salon
        data:
          message: Au revoir!
          data:
            type: announce

  - alias: TV pas sur Box
    trigger:
      - platform: template
        value_template: "{{ is_state_attr('media_player.rx_v475','source','Box') }}"
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: media_player.sony_bravia_tv
          state: "HDMI 3/ARC"
          attribute: source
    action:
      - service: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"

  - alias: TV pas sur Switch
    trigger:
      - platform: template
        value_template: "{{ is_state_attr('media_player.rx_v475','source','PS3') }}"
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: media_player.sony_bravia_tv
          state: "HDMI 3/ARC"
          attribute: source
    action:
      - service: media_player.select_source
        data:
          entity_id: media_player.sony_bravia_tv
          source: "HDMI 3/ARC"
  # - alias: Playlist on Spotify
  #   trigger:
  #     - platform: state
  #       entity_id: sensor.xiaomi_nawak
  #       to: "hold"
  #   action:
  #     - service: media_player.play_media
  #       data:
  #         entity_id: media_player.echo_salon
  #         media_content_id: Playlist Best of
  #         media_content_type: SPOTIFY
