###############################################################
# Automation
###############################################################
automation:
  - alias: Humidité SdB
    description: "Humidité SdB"
    trigger:
      - entity_id: sensor.xiaomi_temp_sdb_humidity
        above: 90
        platform: numeric_state
        for:
          minutes: 30
      - entity_id: sensor.xiaomi_temp_sdb_humidity
        above: 80
        platform: numeric_state
        for:
          minutes: 60
    condition:
      - condition: time
        after: "07:00:00"
        before: "20:00:00"
    action:
      - service: notify.mobile_app_iphone_de_le_gone
        data:
          data:
            push:
              badge: 5
              thread-id: home-assistant
          message: Quelqu'un pourrait ouvrir la fenêtre?
          title: Il y a trop d'humidité dans la Salle de Bain
      - service: notify.alexa_media_echo_salon
        data:
          message: Il y a trop d'humidité dans la Salle de Bain. Quelqu'un pourrait ouvrir la fenêtre?
          data:
            type: announce
            method: all

  - alias: Alerte humidité Salle de Bain
    trigger:
      - entity_id: light.sonoff_salle_de_bain
        platform: state
        to: "off"
    condition:
      - condition: numeric_state
        entity_id: sensor.xiaomi_temp_sdb_temperature
        below: 20
      - condition: numeric_state
        entity_id: sensor.xiaomi_temp_sdb_humidity
        above: 80
      - condition: time
        after: "07:00:00"
        before: "20:00:00"
    action:
      - service: notify.alexa_media_echo_sdb
        data:
          message: Avez vous pensé à ouvrir la fenêtre?
          data:
            type: announce
