###############################################################
# Automation
###############################################################
automation:
  - alias: Fuite cuisine
    trigger:
      - trigger: state
        entity_id: binary_sensor.xiaomi_fuite_cuisine_water_leak
        from: "off"
        to: "on"
    actions:
      - service: light.turn_on
        data:
          entity_id: light.gateway_light_7811dcfaa3ee
          color_name: red
          brightness_pct: 100
      - parallel:
          # Salon
          - action: alexa_devices.send_sound
            data:
              device_id: 469a2e22fa36880f8ba14e1fadd9d995
              sound: amzn_sfx_scifi_alarm_01
          # Cuisine
          - action: alexa_devices.send_sound
            data:
              device_id: da05d4e93809561b0b1b7e9dbe2ea3b5
              sound: amzn_sfx_scifi_alarm_01
      - action: notify.send_message
        target:
          entity_id:
            - notify.echo_de_cleo_announce
            - notify.echo_salon_announce
            - notify.echo_sdb_announce
            - notify.echo_cuisine_announce
        data:
          message: Alerte! Fuite d'eau détectée à la cuisine!
      - service: notify.mobile_app_iphone_amadeus
        alias: "Notification fuite cuisine"
        data:
          data:
            push:
              interruption-level: critical
          message: Vite sortez la serpillère!
          title: Une fuite d'eau a été détectée à la cuisine!
      - service: xiaomi_aqara.play_ringtone
        data_template:
          gw_mac: !secret xiaomi_gateway_mac
          ringtone_id: "{{ states.input_select.sirenes_gateway.state.split('-')[0] }}"
          ringtone_vol: "{{ states.input_number.gateway_volume.state|int }}"

  - alias: Fuite cuisine terminée
    trigger:
      - trigger: state
        entity_id: binary_sensor.xiaomi_fuite_cuisine_water_leak
        from: "on"
        to: "off"
    action:
      - service: light.turn_off
        data:
          entity_id: light.gateway_light_7811dcfaa3ee

  - alias: Fuite SdB
    trigger:
      - trigger: state
        entity_id: binary_sensor.xiaomi_fuite_sdb_water_leak
        from: "off"
        to: "on"
    action:
      - service: light.turn_on
        data:
          entity_id: light.gateway_light_7811dcfaa3ee
          color_name: red
          brightness_pct: 100
      - service: light.turn_on
        data:
          entity_id: light.gateway_light_7811dcfaa3ee
          color_name: red
          brightness_pct: 100
      - parallel:
          # Salon
          - action: alexa_devices.send_sound
            data:
              device_id: 469a2e22fa36880f8ba14e1fadd9d995
              sound: amzn_sfx_scifi_alarm_01
          # Cuisine
          - action: alexa_devices.send_sound
            data:
              device_id: da05d4e93809561b0b1b7e9dbe2ea3b5
              sound: amzn_sfx_scifi_alarm_01
      - action: notify.send_message
        target:
          entity_id:
            - notify.echo_de_cleo_announce
            - notify.echo_salon_announce
            - notify.echo_sdb_announce
            - notify.echo_cuisine_announce
        data:
          message: Une fuite d'eau a été détectée à la salle de bain!
      - service: notify.mobile_app_iphone_amadeus
        alias: "Notification fuite salle de bain"
        data:
          data:
            push:
              interruption-level: critical
          message: Vite sortez la serpillère!
          title: Une fuite d'eau a été détectée à la salle de bain!
      - service: xiaomi_aqara.play_ringtone
        data_template:
          gw_mac: !secret xiaomi_gateway_mac
          ringtone_id: "{{ states.input_select.sirenes_gateway.state.split('-')[0] }}"
          ringtone_vol: "{{ states.input_number.gateway_volume.state|int }}"

  - alias: Fuite SdB terminée
    trigger:
      - trigger: state
        entity_id: binary_sensor.xiaomi_fuite_sdb_water_leak
        from: "on"
        to: "off"
    action:
      - service: light.turn_off
        data:
          entity_id: light.gateway_light_7811dcfaa3ee
