###############################################################
# Lights
###############################################################

light:
  - platform: mqtt
    name: "SàM"
    state_topic: "stat/home/dining/light/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/dining/light/POWER"
    availability_topic: "tele/home/dining/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Cléo"
    state_topic: "stat/home/cleo/light/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/cleo/light/POWER"
    availability_topic: "tele/home/cleo/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Salon"
    state_topic: "stat/home/living/light/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/living/light/POWER"
    availability_topic: "tele/home/living/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Chambre"
    state_topic: "stat/home/parents/light/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/parents/light/POWER"
    availability_topic: "tele/home/parents/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "S20"
    state_topic: "stat/home/s20/light/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/s20/light/POWER"
    availability_topic: "tele/home/s20/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Entrée 1"
    state_topic: "stat/home/entrance/light1/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/entrance/light1/POWER"
    availability_topic: "tele/home/entrance/light1/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Entrée 2"
    state_topic: "stat/home/entrance/light2/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/entrance/light2/POWER"
    availability_topic: "tele/home/entrance/light2/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Entrée 3"
    state_topic: "stat/home/entrance/light3/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/entrance/light3/POWER"
    availability_topic: "tele/home/entrance/light3/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Cuisine"
    state_topic: "stat/home/kitchen/light/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/kitchen/light/POWER"
    availability_topic: "tele/home/kitchen/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Salle de Bain"
    state_topic: "stat/home/bathroom/light/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/bathroom/light/POWER"
    availability_topic: "tele/home/bathroom/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Couloir"
    state_topic: "stat/home/corridor/light/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/corridor/light/POWER"
    availability_topic: "tele/home/corridor/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "WC"
    state_topic: "stat/home/wc/light/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/wc/light/POWER"
    availability_topic: "tele/home/wc/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "WC Wall"
    state_topic: "stat/home/wc-wall/light/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/wc-wall/light/POWER"
    availability_topic: "tele/home/wc-wall/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Shoes"
    state_topic: "stat/home/shoes/light/RESULT"
    state_value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/home/shoes/light/POWER"
    availability_topic: "tele/home/shoes/light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: group
    name: Groupe entree
    entities:
      - light.entree_1
      - light.entree_2
      - light.entree_3

###############################################################
# Scripts
###############################################################

###############################################################
# Automation
###############################################################
automation:
  # ----- SaM et Salon

  - alias: Lumière salon
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sam_action
        to: "single_right"
    action:
      - service: light.toggle
        entity_id: light.salon

  - alias: Lumière salon indirecte
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sam_action
        to: "double_right"
    action:
      - entity_id: switch.osram_tv
        service: switch.toggle

  - alias: Lumière salle à manger
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sam_action
        to: "single_left"
    action:
      - service: light.toggle
        entity_id: light.sam

  - alias: Lumière salle à manger indirecte
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sam_action
        to: "double_left"
    action:
      - entity_id: switch.osram_bureau
        service: switch.toggle

  # ----- Cleo

  - alias: Lumière Cléo
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_cleo_action
        to: "single"
    action:
      - service: light.toggle
        entity_id: light.cleo

  - alias: Lumière Cléo indirecte
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_cleo_action
        to: "double"
    action:
      - entity_id: switch.osram_cleo
        service: switch.toggle

  # ----- Chambre

  - alias: Lumière lit Parents
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_bedroom_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_marina_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_fabrice_action
        to: "single"
    action:
      - service: light.toggle
        entity_id: light.chambre

  - alias: Lumière lit Parents indirect
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_bedroom_action
        to: "double"
      - platform: state
        entity_id: sensor.xiaomi_marina_action
        to: "double"
      - platform: state
        entity_id: sensor.xiaomi_fabrice_action
        to: "hold"
      - platform: state
        entity_id: sensor.xiaomi_marina_action
        to: "hold"
      - platform: state
        entity_id: sensor.xiaomi_fabrice_action
        to: "double"
      - platform: state
        entity_id: sensor.xiaomi_shoes_action
        to: "double"
    action:
      - entity_id: switch.osram_chambre
        service: switch.toggle

  # ----- Cuisine

  - alias: Lumière Cuisine
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_cuisine_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_cuisine_action
        to: "double"
    action:
      - service: light.toggle
        entity_id: light.cuisine

  # ----- Entrée

  - alias: Lumière entrée
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_entree_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_entree_couloir_action
        to: "single_left"
    action:
      - service: light.toggle
        entity_id: light.entree_1,light.entree_2,light.entree_3

  # ----- SDB

  - alias: Lumière salle de bain
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sdb_action
        to: "single_left"
      - platform: state
        entity_id: sensor.xiaomi_sdb_action
        to: "double_left"
    action:
      - service: light.toggle
        entity_id: light.salle_de_bain

  # ----- Couloir
  - alias: Lumière couloir
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_couloir_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_entree_couloir_action
        to: "single_right"
      - platform: state
        entity_id: sensor.xiaomi_sdb_action
        to: "single_right"
    action:
      - service: light.toggle
        entity_id: light.couloir
      - service: timer.start
        data:
          entity_id: timer.couloir

  - alias: Lumière couloir auto off
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.couloir
    action:
      service: light.turn_off
      data:
        entity_id:
          - light.couloir

  # ----- Chaussures
  - alias: Lumière chaussures
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_shoes_action
        to: "single"
    action:
      - service: light.toggle
        entity_id: light.shoes
      - service: timer.start
        data:
          entity_id: timer.chaussures

  - alias: Lumière chaussures auto off
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.chaussures
    action:
      service: light.turn_off
      data:
        entity_id:
          - light.shoes

  # ----- WC
  - alias: Lumière WC
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_wc_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_wc_action
        to: "double"
    condition:
      condition: not
      conditions:
        - condition: time
          after: "22:00:00"
          before: "08:00:00"
    action:
      - service: light.toggle
        entity_id: light.wc
      - service: light.toggle
        entity_id: light.wc_wall

  - alias: Lumière WC nuit
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_wc_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_wc_action
        to: "double"
    condition:
      condition: time
      after: "22:00:00"
      before: "08:00:00"
    action:
      - service: light.toggle
        entity_id: light.wc_wall

  - alias: Lumière WC resync off
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_wc_action
        to: "hold"
    action:
      - service: light.turn_off
        entity_id: light.wc_wall, light.wc

  # ----- All

  - alias: Sortir maison (lumières)
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_entree_action
        to: "hold"
    condition:
      - condition: state
        entity_id: alarm_control_panel.maison
        state: disarmed
    action:
      - service: light.turn_off
        entity_id: all

###############################################################
# Timer
###############################################################

timer:
  chaussures:
    duration: "00:01:00"
  couloir:
    duration: "00:01:00"
