###############################################################
# Inputs
###############################################################

input_boolean:
  automated_lights:
    name: Automated lights
    icon: mdi:auto-fix

###############################################################
# Lights
###############################################################

light:
  - platform: group
    name: Groupe entree
    entities:
      - light.sonoff_entree_1
      - light.sonoff_entree_2
      - light.sonoff_entree_3

  - platform: group
    name: Toutes lumieres
    entities:
      - light.sonoff_entree_1
      - light.sonoff_entree_2
      - light.sonoff_entree_3
      - light.sonoff_chambre
      - light.sonoff_cleo
      - light.sonoff_couloir
      - light.sonoff_cuisine
      - light.sonoff_salle_de_bain
      - light.sonoff_salon
      - light.sonoff_sam
      - light.sonoff_shoes
      - light.sonoff_wc
      - light.sonoff_wc_wall

###############################################################
# Scripts
###############################################################

###############################################################
# Automation
###############################################################
automation:
  # ----- SaM et Salon

  - alias: Lumière salon
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sam_action
        to: "single_right"
    action:
      - service: light.toggle
        entity_id: light.sonoff_salon

  - alias: Lumière salle à manger
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sam_action
        to: "single_left"
    action:
      - service: light.toggle
        entity_id: light.sonoff_sam
  # ----- Cleo

  - alias: Lumière Cléo
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_cleo_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_cleo_up_action
        to: "single"
    action:
      - service: light.toggle
        entity_id: light.sonoff_cleo

  - alias: Lumière Cléo indirecte
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_cleo_action
        to: "double"
      - platform: state
        entity_id: sensor.xiaomi_cleo_up_action
        to: "double"
    action:
      - entity_id: switch.osram_cleo
        service: switch.toggle

      - entity_id: switch.osram_globe
        service: switch.toggle

  # ----- Chambre

  - alias: Lumière lit Parents
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_bedroom_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_chambre_gauche_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_chambre_droite_action
        to: "single"
    action:
      - service: light.toggle
        entity_id: light.sonoff_chambre

  - alias: Lumière lit Parents indirect
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_bedroom_action
        to: "double"
      - platform: state
        entity_id: sensor.xiaomi_chambre_gauche_action
        to: "double"
      - platform: state
        entity_id: sensor.xiaomi_chambre_droite_action
        to: "double"
      - platform: state
        entity_id: sensor.xiaomi_shoes_action
        to: "double"
      - platform: state
        entity_id: sensor.xiaomi_chambre_droite_action
        to: "hold"
      - platform: state
        entity_id: sensor.xiaomi_chambre_gauche_action
        to: "hold"
    action:
      - entity_id: switch.osram_chambre
        service: switch.toggle

  # ----- Cuisine

  - alias: Auto Cuisine
    use_blueprint:
      path: homeassistant/motion_light.yaml
      input:
        motion_sensor: binary_sensor.xiaomi_presence_cuisine_occupancy
        motion_sensor_2: binary_sensor.tuya_presence_cuisine_presence
        switch_sensor: sensor.xiaomi_cuisine_action
        primary_light: light.sonoff_cuisine
        light_sensor: sensor.tuya_presence_cuisine_illuminance
        min_lux: 1200
        no_motion_wait: 120

  # - alias: Lumière Cuisine
  #   trigger:
  #     - platform: state
  #       entity_id: sensor.xiaomi_cuisine_action
  #       to: "single"
  #   condition:
  #     - condition: state
  #       entity_id: timer.cuisine_idle
  #       state: idle
  #   action:
  #     - service: light.toggle
  #       entity_id: light.sonoff_cuisine
  #     - service: timer.start
  #       target:
  #         entity_id: timer.cuisine_idle

  # - alias: Auto Cuisine
  #   use_blueprint:
  #     path: homeassistant/motion_light_on.yaml
  #     input:
  #       motion_sensor: binary_sensor.xiaomi_presence_cuisine_occupancy
  #       light: light.sonoff_cuisine
  #       light_sensor: sensor.xiaomi_presence_cuisine_illuminance
  #       timer: timer.cuisine_idle
  #       min_lux: 20

  # - alias: Auto Cuisine off
  #   use_blueprint:
  #     path: homeassistant/motion_light_off.yaml
  #     input:
  #       motion_sensor: binary_sensor.xiaomi_presence_cuisine_occupancy
  #       light: light.sonoff_cuisine
  #       timer: timer.cuisine_idle

  # - alias: Auto Cuisine 2
  #   use_blueprint:
  #     path: homeassistant/motion_light_on.yaml
  #     input:
  #       motion_sensor: binary_sensor.tuya_presence_cuisine_presence
  #       light_sensor: sensor.tuya_presence_cuisine_illuminance
  #       light: light.sonoff_cuisine
  #       timer: timer.cuisine_idle
  #       min_lux: 2000

  # - alias: Auto Cuisine off 2
  #   use_blueprint:
  #     path: homeassistant/motion_light_off.yaml
  #     input:
  #       motion_sensor: binary_sensor.tuya_presence_cuisine_presence
  #       light: light.sonoff_cuisine
  #       timer: timer.cuisine_idle

  # - alias: Auto Cuisine radar
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.tuya_presence_cuisine_presence
  #   action:
  #     - service: light.turn_{{trigger.to_state.state}}
  #       entity_id: light.sonoff_cuisine

  # - alias: Lumière cuisine autoresync
  #   trigger:
  #     - platform: numeric_state
  #       entity_id: binary_sensor.xiaomi_presence_cuisine_occupancy
  #       attribute: illuminance
  #       above: 20
  #   condition:
  #     - condition: state
  #       entity_id: light.sonoff_cuisine
  #       state: "on"
  #   action:
  #     - service: light.turn_off
  #       entity_id: light.sonoff_cuisine

  # ----- Entrée

  - alias: Lumière entrée
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_entree_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_entree_couloir_action
        to: "single_left"
    action:
      - service: light.toggle
        entity_id: light.sonoff_entree_1,light.sonoff_entree_2,light.sonoff_entree_3
      - service: timer.start
        data:
          entity_id: timer.entree

  - alias: Lumière entree auto off
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.entree
    action:
      service: light.turn_off
      data:
        entity_id: light.sonoff_entree_1,light.sonoff_entree_2,light.sonoff_entree_3

  - alias: Porte ouverte
    trigger:
      - platform: state
        entity_id: binary_sensor.xiaomi_door_contact
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.maison
        state: disarmed
    action:
      - service: light.turn_on
        data:
          entity_id: light.gateway_light_7811dcfaa3ee
          color_name: yellow
          brightness_pct: 100

  - alias: Porte fermée
    trigger:
      - platform: state
        entity_id: binary_sensor.xiaomi_door_contact
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: alarm_control_panel.maison
        state: disarmed
    action:
      - service: light.turn_off
        data:
          entity_id: light.gateway_light_7811dcfaa3ee

  # ----- SDB

  - alias: Lumière salle de bain
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sdb_action
        to: "single_left"
      - platform: state
        entity_id: sensor.xiaomi_sdb_action
        to: "double_left"
    action:
      - service: light.toggle
        entity_id: light.sonoff_salle_de_bain

  # ----- Couloir
  - alias: Lumière couloir
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_couloir_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_entree_couloir_action
        to: "single_right"
      - platform: state
        entity_id: sensor.xiaomi_sdb_action
        to: "single_right"
    action:
      - service: light.toggle
        entity_id: light.sonoff_couloir
      - service: timer.start
        data:
          entity_id: timer.couloir

  - alias: Lumière couloir permanent
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_couloir_action
        to: "double"
    action:
      - service: light.toggle
        entity_id: light.sonoff_couloir

  - alias: Lumière couloir auto off
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.couloir
    action:
      service: light.turn_off
      data:
        entity_id:
          - light.sonoff_couloir

  # ----- Chaussures
  - alias: Lumière chaussures
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_shoes_action
        to: "single"
    action:
      - service: light.toggle
        target:
          entity_id: light.sonoff_shoes
      - service: timer.start
        data:
          entity_id: timer.chaussures

  - alias: Lumière chaussures auto off
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.chaussures
    action:
      service: light.turn_off
      data:
        entity_id:
          - light.sonoff_shoes

  # ----- WC

  # - alias: Lumière WC
  #   trigger:
  #     - platform: state
  #       entity_id: sensor.xiaomi_wc_action
  #       to: "single"
  #     - platform: state
  #       entity_id: sensor.xiaomi_wc_action
  #       to: "double"
  #   condition:
  #     condition: not
  #     conditions:
  #       - condition: time
  #         after: "22:00:00"
  #         before: "08:00:00"
  #   action:
  #     - service: light.toggle
  #       entity_id: light.sonoff_wc
  #     - service: light.toggle
  #       entity_id: light.sonoff_wc_wall

  # - alias: Lumière WC nuit
  #   trigger:
  #     - platform: state
  #       entity_id: sensor.xiaomi_wc_action
  #       to: "single"
  #     - platform: state
  #       entity_id: sensor.xiaomi_wc_action
  #       to: "double"
  #   condition:
  #     condition: time
  #     after: "22:00:00"
  #     before: "08:00:00"
  #   action:
  #     - service: light.toggle
  #       entity_id: light.sonoff_wc_wall

  - alias: Lumière WC resync off
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_wc_action
        to: "hold"
    action:
      - service: light.turn_off
        entity_id: light.sonoff_wc_wall, light.sonoff_wc

  # - alias: Lumière WC autoresync
  #   trigger:
  #     platform: time
  #     at: "08:00:00"
  #   condition:
  #     - condition: state
  #       entity_id: light.sonoff_wc_wall
  #       state: "on"
  #   action:
  #     - service: light.turn_on
  #       entity_id: light.sonoff_wc

  # - alias: Lumière WC autoresync night
  #   trigger:
  #     platform: time
  #     at: "22:00:00"
  #   condition:
  #     - condition: state
  #       entity_id: light.sonoff_wc
  #       state: "on"
  #   action:
  #     - service: light.turn_off
  #       entity_id: light.sonoff_wc

  # - alias: Auto WC radar
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.tuya_presence_wc_presence
  #   action:
  #     - service: light.turn_{{trigger.to_state.state}}
  #       entity_id: light.sonoff_wc_wall, light.sonoff_wc

  # - alias: Auto WC radar
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.tuya_presence_wc_presence
  #       to: "on"
  #       from: "off"
  #   condition:
  #     condition: time
  #     after: "08:00:00"
  #     before: "23:59:00"
  #   action:
  #     - service: light.turn_on
  #       entity_id: light.sonoff_wc
  #     - service: light.turn_on
  #       entity_id: light.sonoff_wc_wall

  # - alias: Auto WC radar
  #   use_blueprint:
  #     path: homeassistant/motion_light_on.yaml
  #     input:
  #       motion_sensor: binary_sensor.tuya_presence_wc_presence
  #       light_sensor: sensor.tuya_presence_wc_illuminance
  #       light: light.sonoff_wc,light.sonoff_wc_wall
  #       timer: timer.wc_idle
  #       min_lux: 2000

  - alias: Auto WC radar
    use_blueprint:
      path: homeassistant/motion_light.yaml
      input:
        motion_sensor: binary_sensor.tuya_presence_wc_presence
        switch_sensor: sensor.xiaomi_wc_action
        primary_light: light.sonoff_wc
        secondary_light: light.sonoff_wc_wall
        light_sensor: sensor.tuya_presence_wc_illuminance
        min_lux: 2000
        no_motion_wait: 300
        day_start_hour: "08:00:00"
        night_start_hour: "22:00:00"

  # ----- All

  - alias: Tout eteindre
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_entree_action
        to: "double"
    action:
      - service: light.turn_off
        entity_id: light.toutes_lumieres

  - alias: Sortir maison (lumières)
    triggers:
      - trigger: state
        entity_id: sensor.xiaomi_entree_action
        to: "hold"
    conditions:
      - condition: state
        entity_id: binary_sensor.xiaomi_door_contact
        state: "on"
    actions:
      - action: light.turn_off
        entity_id: light.toutes_lumieres

  - alias: "Anti moustiques on"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.maison
        to: "armed_away"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.tuya_cuisine

  - alias: "Anti moustiques off"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.maison
        to: "disarmed"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.tuya_cuisine

  - alias: "Anti moustiques toggle"
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_cuisine_action
        to: "double"
    action:
      - service: switch.toggle
        target:
          entity_id: switch.tuya_cuisine

  # ----- Spare

  - alias: Test
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_spare_action
        to: "single"
    action:
      - service: light.toggle
        entity_id: light.sonoff_shoes

###############################################################
# Timer
###############################################################

timer:
  chaussures:
    duration: "00:05:00"
  couloir:
    duration: "00:05:00"
  entree:
    duration: "00:05:00"
