###############################################################
# Lights
###############################################################

light:
  - platform: group
    name: Groupe entree
    entities:
      - light.sonoff_entree_1
      - light.sonoff_entree_2
      - light.sonoff_entree_3

###############################################################
# Scripts
###############################################################

###############################################################
# Automation
###############################################################
automation:
  # ----- SaM et Salon

  - alias: Lumière salon
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sam_action
        to: "single_right"
    action:
      - service: light.toggle
        entity_id: light.sonoff_salon

  - alias: Lumière salon indirecte
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sam_action
        to: "double_right"
    action:
      - entity_id: switch.osram_tv
        service: switch.toggle

  - alias: Lumière salle à manger
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sam_action
        to: "single_left"
    action:
      - service: light.toggle
        entity_id: light.sonoff_sam

  - alias: Lumière salle à manger indirecte
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sam_action
        to: "double_left"
    action:
      - entity_id: switch.osram_bureau
        service: switch.toggle

  # ----- Cleo

  - alias: Lumière Cléo
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_cleo_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_cleo_up_action
        to: "double"
    action:
      - service: light.toggle
        entity_id: light.sonoff_cleo

  - alias: Lumière Cléo indirecte
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_cleo_action
        to: "double"
      - platform: state
        entity_id: sensor.xiaomi_cleo_up_action
        to: "single"
    action:
      - entity_id: switch.osram_cleo
        service: switch.toggle

  # ----- Chambre

  - alias: Lumière lit Parents
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_bedroom_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_marina_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_fabrice_action
        to: "single"
    action:
      - service: light.toggle
        entity_id: light.sonoff_chambre

  - alias: Lumière lit Parents indirect
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_bedroom_action
        to: "double"
      - platform: state
        entity_id: sensor.xiaomi_marina_action
        to: "double"
      - platform: state
        entity_id: sensor.xiaomi_fabrice_action
        to: "double"
      - platform: state
        entity_id: sensor.xiaomi_shoes_action
        to: "double"
      - platform: state
        entity_id: sensor.xiaomi_fabrice_action
        to: "hold"
      - platform: state
        entity_id: sensor.xiaomi_marina_action
        to: "hold"
      - platform: state
        entity_id: sensor.xiaomi_entree_couloir
        to: "single_both"
    action:
      - entity_id: switch.osram_chambre
        service: switch.toggle

  # ----- Cuisine

  - alias: Lumière Cuisine
    trigger:
      - platform: device
        domain: mqtt
        device_id: 45e15a3d039bd6149354b4d0008f51dc
        type: action
        subtype: single
        discovery_id: 0x00158d00031b5437 action_single
    #      - platform: state
    #        entity_id: sensor.xiaomi_cuisine_action
    #        to: "single"
    #      - platform: state
    #        entity_id: sensor.xiaomi_cuisine_action
    #        to: "double"
    action:
      - service: light.toggle
        entity_id: light.sonoff_cuisine

  # ----- Entrée

  - alias: Lumière entrée
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_entree_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_entree_couloir_action
        to: "single_left"
    action:
      - service: light.toggle
        entity_id: light.sonoff_entree_1,light.sonoff_entree_2,light.sonoff_entree_3

  # ----- SDB

  - alias: Lumière salle de bain
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sdb_action
        to: "single_left"
      - platform: state
        entity_id: sensor.xiaomi_sdb_action
        to: "double_left"
    action:
      - service: light.toggle
        entity_id: light.sonoff_salle_de_bain

  # ----- Couloir
  - alias: Lumière couloir
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_couloir_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_entree_couloir_action
        to: "single_right"
      - platform: state
        entity_id: sensor.xiaomi_sdb_action
        to: "single_right"
    action:
      - service: light.toggle
        entity_id: light.sonoff_couloir
      - service: timer.start
        data:
          entity_id: timer.couloir

  - alias: Lumière couloir auto off
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.couloir
    action:
      service: light.turn_off
      data:
        entity_id:
          - light.sonoff_couloir

  # ----- Chaussures
  - alias: Lumière chaussures
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_shoes_action
        to: "single"
    action:
      - service: light.toggle
        target:
          entity_id: light.sonoff_shoes
      - service: timer.start
        data:
          entity_id: timer.chaussures

  - alias: Lumière chaussures auto off
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.chaussures
    action:
      service: light.turn_off
      data:
        entity_id:
          - light.sonoff_shoes

  # ----- WC
  - alias: Lumière WC
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_wc_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_wc_action
        to: "double"
    condition:
      condition: not
      conditions:
        - condition: time
          after: "22:00:00"
          before: "08:00:00"
    action:
      - service: light.toggle
        entity_id: light.sonoff_wc
      - service: light.toggle
        entity_id: light.sonoff_wc_wall

  - alias: Lumière WC nuit
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_wc_action
        to: "single"
      - platform: state
        entity_id: sensor.xiaomi_wc_action
        to: "double"
    condition:
      condition: time
      after: "22:00:00"
      before: "08:00:00"
    action:
      - service: light.toggle
        entity_id: light.sonoff_wc_wall

  - alias: Lumière WC resync off
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_wc_action
        to: "hold"
    action:
      - service: light.turn_off
        entity_id: light.sonoff_wc_wall, light.sonoff_wc

  # ----- All

  - alias: Sortir maison (lumières)
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_entree_action
        to: "hold"
    condition:
      - condition: state
        entity_id: alarm_control_panel.maison
        state: disarmed
    action:
      - service: light.turn_off
        entity_id: all

  # ----- Spare

  - alias: Test
    trigger:
      #- platform: state
      #  entity_id: sensor.xiaomi_spare_action
      #  to: "single"
      - platform: device
        domain: mqtt
        device_id: a5d6d08fc57bdc0a4bd0caad05fad841
        type: action
        subtype: single
        discovery_id: 0x00158d0005441db0 action_single
    action:
      - service: light.toggle
        entity_id: light.sonoff_shoes

###############################################################
# Timer
###############################################################

timer:
  chaussures:
    duration: "00:01:00"
  couloir:
    duration: "00:01:00"
