###############################################################
# Inputs
###############################################################

###############################################################
# Lights
###############################################################

###############################################################
# Scripts
###############################################################

###############################################################
# Automation
###############################################################
automation:
  - alias: Allumer sapin
    trigger:
      platform: time
      at: "07:40:00"
    action:
      - service: switch.turn_on
        entity_id: switch.tuya_sapin

  - alias: Eteindre sapin
    trigger:
      platform: time
      at: "20:30:00"
    action:
      - service: switch.turn_off
        entity_id: switch.tuya_sapin

  - alias: Toggle sapin
    trigger:
      - platform: state
        entity_id: sensor.xiaomi_sam_action
        to: "single_both"
    action:
      - service: switch.toggle
        entity_id: switch.tuya_sapin
