###############################################################
# Sensors
###############################################################

sensor:

###############################################################
# Automation
###############################################################

automation:
  - alias: Risque de pluie
    trigger:
      platform: time
      at: "07:30:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: numeric_state
        entity_id: sensor.nice_rain_chance
        above: 20
    action:
      - alias: ""
        service: notify.mobile_app_iphone_amadeus
        data:
          message: Pense à prendre ton blouson de moto étanche
          title: Risque de pluie
          data:
            push:
              interruption-level: time-sensitive
    id: 6fbc85b1b12f43ff83421c7e0879c21b

  - alias: Il pleut
    trigger:
      platform: time
      at: "07:25:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: state
        entity_id: sensor.nice_weather
        state: Pluie
    action:
      - alias: ""
        data:
          message: Habillez vous en conséquence
          title: Il pleut dehors
          data:
            push:
              interruption-level: time-sensitive
        service: notify.mobile_app_iphone_amadeus
      - action: notify.send_message
        data:
          message: Attention, il pleut dehors.
        target:
          entity_id: notify.echo_salon_announce

  ##################################### Trajets

  - alias: Temps de trajet
    trigger:
      platform: time
      at: "07:28:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: numeric_state
        entity_id: sensor.fabrice_to_work
        above: 20
    action:
      - alias: ""
        service: notify.mobile_app_iphone_amadeus
        data:
          message: "{{ states('sensor.fabrice_to_work') }} minutes"
          title: Temps de trajet estimé
      - action: notify.send_message
        data:
          message: Temps de trajet particulièrement long de {{ states("sensor.fabrice_to_work") }} minutes
        target:
          entity_id: notify.echo_salon_announce

  - alias: Temps de trajet retour
    trigger:
      platform: time
      at: "18:00:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: numeric_state
        entity_id: sensor.fabrice_back_home
        above: 20
    action:
      - alias: ""
        service: notify.mobile_app_iphone_amadeus
        data:
          message: "{{ states('sensor.fabrice_back_home') }} minutes"
          title: Temps de trajet estimé
