
###############################################################
# Sensors
###############################################################

sensor:
  
  - platform: waze_travel_time
    name: "Fabrice to Work"
    origin: zone.home
    destination: zone.amadeus_bel_air
    region: 'EU'
    vehicle_type: motorcycle
  - platform: waze_travel_time
    name: "Fabrice back Home"
    origin: zone.amadeus_bel_air
    destination: zone.home
    region: 'EU'
    vehicle_type: motorcycle
  - platform: waze_travel_time
    name: "Marina to Work"
    origin: zone.home
    destination: zone.caf_nice_europe
    region: 'EU'
  - platform: waze_travel_time
    name: "Marina back Home"
    origin: zone.caf_nice_europe
    destination: zone.home
    region: 'EU'

###############################################################
# Automation
###############################################################

automation:

  
  - alias: Risque de pluie
    trigger:
      platform: time
      at: "07:30:00"
    condition:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: switch.conchita_schedule
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.nice_rain_chance
      above: 20
    action:
    - alias: ''
      data:
        data:
          push:
            badge: 5
            thread-id: home-assistant
        message: Pense à prendre ton blouson de moto étanche
        title: Risque de pluie
      service: notify.ios_iphone_de_le_gone
    id: 6fbc85b1b12f43ff83421c7e0879c21b
  
  - alias: Il pleut
    trigger:
      platform: time
      at: "07:25:00"
    condition:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: switch.conchita_schedule
      state: 'on'
    - condition: state
      entity_id: sensor.nice_weather
      state: Pluie
    action:
    - alias: ''
      data:
        data:
          push:
            badge: 5
            thread-id: home-assistant
        message: Habillez vous en conséquence
        title: Il pleut dehors
      service: notify.ios_iphone_de_le_gone
    - service: notify.alexa_media_echo_salon
      data:
        target: media_player.alexa
        message: Attention, il pleut dehors.
        data:
          type: announce
          method: all
    id: 41d536435d6346bca25d4eabb55c7d35

##################################### Trajets
  - alias: Temps de trajet
    trigger:
      platform: time
      at: "07:32:00"
    condition:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: switch.conchita_schedule
      state: 'on'
    action:
    - alias: ''
      service: notify.ios_iphone_de_le_gone
      data:
        message: '{{ states(''sensor.fabrice_to_work'') }} minutes'
        title: Temps de trajet estimé
        data:
          push:
            badge: 5
            thread-id: home-assistant
    - service: notify.alexa_media_echo_salon
      data:
        target: media_player.alexa
        message: Temps de trajet estimé à {{ states('sensor.fabrice_to_work') }} minutes
        data:
          type: announce
          method: all
  
  - alias: Temps de trajet retour
    trigger:
      platform: time
      at: "18:00:00"
    condition:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: switch.conchita_schedule
      state: 'on'
    action:
    - alias: ''
      service: notify.ios_iphone_de_le_gone
      data:
        message: '{{ states(''sensor.fabrice_to_work'') }} minutes'
        title: Temps de trajet estimé
        data:
          push:
            badge: 5
            thread-id: home-assistant
