###############################################################
# Sensors
###############################################################

sensor:

###############################################################
# Automation
###############################################################

automation:
  - alias: Risque de pluie
    trigger:
      platform: time
      at: "07:30:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: numeric_state
        entity_id: sensor.nice_rain_chance
        above: 20
    action:
      - alias: ""
        service: notify.mobile_app_iphone_de_le_gone
        data:
          message: Pense à prendre ton blouson de moto étanche
          title: Risque de pluie
          data:
            push:
              interruption-level: time-sensitive
    id: 6fbc85b1b12f43ff83421c7e0879c21b

  - alias: Il pleut
    trigger:
      platform: time
      at: "07:25:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: state
        entity_id: sensor.nice_weather
        state: Pluie
    action:
      - alias: ""
        data:
          message: Habillez vous en conséquence
          title: Il pleut dehors
          data:
            push:
              interruption-level: time-sensitive
        service: notify.mobile_app_iphone_de_le_gone
      - service: notify.alexa_media_echo_salon
        data:
          message: Attention, il pleut dehors.
          data:
            type: announce

  ##################################### Trajets

  # - alias: Fabrice maison
  #   trigger:
  #     - entity_id: person.fabrice_pipart
  #       platform: state
  #       from: "not_home"
  #       to: "home"
  #   action:
  #     - service: notify.alexa_media_echo_salon
  #       data:
  #         message: Bienvenu à la maison Fabrice!
  #         data:
  #           type: announce

  - alias: Temps de trajet
    trigger:
      platform: time
      at: "07:28:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: numeric_state
        entity_id: sensor.fabrice_to_work
        above: 20
    action:
      - alias: ""
        service: notify.mobile_app_iphone_de_le_gone
        data:
          message: "{{ states('sensor.fabrice_to_work') }} minutes"
          title: Temps de trajet estimé
      - service: notify.alexa_media_echo_salon
        data:
          message: Temps de trajet particulièrement long de {{ states("sensor.fabrice_to_work") }} minutes
          data:
            type: announce
            method: all

  - alias: Temps de trajet retour
    trigger:
      platform: time
      at: "18:00:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.vacations
        state: "off"
      - condition: numeric_state
        entity_id: sensor.fabrice_back_home
        above: 20
    action:
      - alias: ""
        service: notify.mobile_app_iphone_de_le_gone
        data:
          message: "{{ states('sensor.fabrice_back_home') }} minutes"
          title: Temps de trajet estimé
